export const WHOLESALE_PRODUCTS = [
  {
    id: 1,
    sku: "BM-CLASSIC",
    name: "Classic Bánh Mì (Wholesale)",
    category: "Bánh Mì",
    description: "Pre-assembled classic bánh mì, ready to heat and serve.",
    unit: "tray",
    unitPrice: "45.00",
    stockQty: 50,
    isAvailable: true,
    minOrderQty: 2,
  },
  {
    id: 2,
    sku: "PHO-BEEF",
    name: "Beef Pho Broth Base",
    category: "Soups",
    description: "Slow-simmered beef pho broth, 5L container.",
    unit: "container",
    unitPrice: "38.00",
    stockQty: 30,
    isAvailable: true,
    minOrderQty: 1,
  },
  {
    id: 3,
    sku: "RR-PRAWN",
    name: "Prawn Rice Paper Rolls",
    category: "Entrées",
    description: "Fresh prawn rice paper rolls, tray of 20.",
    unit: "tray",
    unitPrice: "55.00",
    stockQty: 25,
    isAvailable: true,
    minOrderQty: 1,
  },
];
