export const STORE_LOCATIONS = [
  {
    id: 1,
    name: "Saigon Express North Hobart",
    address: "335 Elizabeth Street, North Hobart TAS 7000",
    suburb: "North Hobart",
    lat: "-42.8721",
    lng: "147.3219",
    phone: "(03) 6234 1001",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
  {
    id: 2,
    name: "Saigon Express Lounge & Bar",
    address: "329 Elizabeth Street, North Hobart TAS 7000",
    suburb: "North Hobart",
    lat: "-42.8698",
    lng: "147.3225",
    phone: "(03) 6234 1002",
    hours: JSON.stringify({ mon: "11:00 AM – 9:00 PM" }),
    isActive: true,
  },
  {
    id: 3,
    name: "Saigon Express CBD",
    address: "95 Liverpool Street, Hobart TAS 7000",
    suburb: "CBD Hobart",
    lat: "-42.8821",
    lng: "147.3272",
    phone: "(03) 6234 1003",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
  {
    id: 4,
    name: "Saigon Express Sandy Bay (Halal)",
    address: "Shop 4, 236 Sandy Bay Road, Sandy Bay TAS 7005",
    suburb: "Sandy Bay",
    lat: "-42.8945",
    lng: "147.3234",
    phone: "(03) 6234 1004",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
  {
    id: 5,
    name: "Saigon Express Kingston",
    address: "Shop 10, 20 Channel Highway, Kingston TAS 7050",
    suburb: "Kingston",
    lat: "-42.9745",
    lng: "147.3089",
    phone: "(03) 6234 1005",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
  {
    id: 6,
    name: "Saigon Express Glebe Hill",
    address: "Glebe Hill Village, Howrah TAS 7018",
    suburb: "Howrah",
    lat: "-42.8891",
    lng: "147.4067",
    phone: "(03) 6234 1006",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
  {
    id: 7,
    name: "Saigon Express Sorell (Gordon St)",
    address: "12 Gordon Street, Sorell TAS 7172",
    suburb: "Sorell",
    lat: "-42.7812",
    lng: "147.5623",
    phone: "(03) 6234 1007",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
  {
    id: 8,
    name: "Saigon Express Sorell (Gateway)",
    address: "Shop 17, 27 Cole Street, Gateway Shopping Centre, Sorell TAS 7172",
    suburb: "Sorell",
    lat: "-42.7789",
    lng: "147.5589",
    phone: "(03) 6234 1008",
    hours: JSON.stringify({ mon: "11:00 AM – 8:30 PM" }),
    isActive: true,
  },
];

export const MENU_ITEMS = [
  {
    id: 1,
    name: "Classic Bánh Mì",
    category: "Bánh Mì",
    price: "8.50",
    description: "Crispy baguette with pork, pâté, pickled vegetables and fresh herbs.",
    isAvailable: true,
    imageUrl: "/manus-storage/crispyroastporkbanhmi_ce355122.jpg",
    sortOrder: 1,
    isPopular: true,
  },
  {
    id: 2,
    name: "Combination Beef Pho",
    category: "Pho",
    price: "16.50",
    description: "Slow-simmered beef broth with rice noodles, brisket and fresh herbs.",
    isAvailable: true,
    imageUrl: "/manus-storage/pho-1_92a9985e.jpg",
    sortOrder: 2,
    isPopular: true,
  },
  {
    id: 3,
    name: "Prawn Rice Paper Rolls",
    category: "Rice Paper Rolls",
    price: "9.50",
    description: "Fresh prawns wrapped in rice paper with vermicelli and herbs.",
    isAvailable: true,
    imageUrl: "/manus-storage/spring-rolls-2_f1e40ae6.jpg",
    sortOrder: 3,
    isPopular: true,
  },
  {
    id: 4,
    name: "Grilled Pork Bún Bowl",
    category: "Bun Bowl",
    price: "15.50",
    description: "Vermicelli noodles with grilled pork, fresh herbs and nuoc cham.",
    isAvailable: true,
    imageUrl: "/manus-storage/bun-bowl-1_3b12ea6c.jpg",
    sortOrder: 4,
    isPopular: false,
  },
  {
    id: 5,
    name: "Crispy Chicken Bánh Mì",
    category: "Bánh Mì",
    price: "9.00",
    description: "Golden fried chicken with mayo, salad and chilli.",
    isAvailable: true,
    imageUrl: "/manus-storage/banh-mi-2_7d02846f.jpg",
    sortOrder: 5,
    isPopular: true,
  },
  {
    id: 6,
    name: "Seafood Spring Rolls",
    category: "Entrée",
    price: "7.50",
    description: "Crispy rolls filled with prawns and vegetables, served with dipping sauce.",
    isAvailable: true,
    imageUrl: "/manus-storage/entree-seafood-spring-rolls_f060f6bd.jpg",
    sortOrder: 6,
    isPopular: false,
  },
];

export const PROMOTIONS = [
  {
    id: 1,
    title: "Lunch Combo Deal",
    description: "Any bánh mì + drink for just $12. Available Monday–Friday, 11am–2pm.",
    badge: "Limited Time",
    discountLabel: "SAVE $3",
    imageUrl: "/manus-storage/banh-mi-3_465cb7d1.jpg",
    ctaLabel: "Order Now",
    ctaHref: "/menu",
    expiresAt: new Date("2026-06-30"),
  },
  {
    id: 2,
    title: "Family Feast Box",
    description: "Feed the whole family — 4 bánh mì, 2 pho and spring rolls. Perfect for sharing.",
    badge: "Popular",
    discountLabel: "15% OFF",
    imageUrl: "/manus-storage/SaigonFeastBox_6c26a5d8.jpg",
    ctaLabel: "View Menu",
    ctaHref: "/menu",
    expiresAt: null,
  },
  {
    id: 3,
    title: "Catering Special",
    description: "Book catering for 20+ guests and receive complimentary spring rolls on us.",
    badge: "Catering",
    discountLabel: "FREE",
    imageUrl: "/manus-storage/catering-hero-counter_71eb7271.jpg",
    ctaLabel: "Enquire Now",
    ctaHref: "/catering",
    expiresAt: new Date("2026-12-31"),
  },
];

export const WHOLESALE_PRODUCTS = [
  {
    id: 1,
    sku: "BM-CLASSIC",
    name: "Classic Bánh Mì (Wholesale)",
    category: "Bánh Mì",
    description: "Pre-assembled classic bánh mì, ready to heat and serve.",
    unit: "tray",
    unitPrice: "45.00",
    stockQty: 50,
    isAvailable: true,
    minOrderQty: 2,
  },
  {
    id: 2,
    sku: "PHO-BEEF",
    name: "Beef Pho Broth Base",
    category: "Soups",
    description: "Slow-simmered beef pho broth, 5L container.",
    unit: "container",
    unitPrice: "38.00",
    stockQty: 30,
    isAvailable: true,
    minOrderQty: 1,
  },
  {
    id: 3,
    sku: "RR-PRAWN",
    name: "Prawn Rice Paper Rolls",
    category: "Entrées",
    description: "Fresh prawn rice paper rolls, tray of 20.",
    unit: "tray",
    unitPrice: "55.00",
    stockQty: 25,
    isAvailable: true,
    minOrderQty: 1,
  },
];
