import type { AustralianStateCode, OrderFulfillmentMethod } from "@/types/WholesaleB2BOrder";

export type CateringOrderReviewForm = {
  customer_name: string;
  customer_email: string;
  customer_phone: string;
  event_date: string;
  guest_count: string;
  requested_fulfillment_method: OrderFulfillmentMethod;
  requested_pick_up_store_id: number | null;
  shipping_dba_name: string;
  shipping_address: string;
  shipping_city: string;
  shipping_state: AustralianStateCode;
  shipping_postal_code: string;
  shipping_country: string;
  shipping_preferred_window: string;
  billing_legal_name: string;
  billing_tax_id: string | null;
  billing_address: string;
  billing_street_2: string | null;
  billing_city: string;
  billing_state: string;
  billing_postal_code: string;
  billing_country: string;
  notes: string | null;
  subtotal: number;
  coupon_code: string | null;
  coupon_discount: number;
  wholesale_discount: number;
  tax_total: number;
  shipping_fee: number;
  grand_total: number;
};
