-- Public blog / news posts (e.g. /news listing and /news/[slug] detail pages).
--
-- Schema mirrors news article layout: category badge, publish date,
-- view count, title, excerpt, hero image, HTML body, tags, optional wholesale CTA,
-- and manually curated related posts.

create table public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  excerpt text,
  content text not null,
  category text not null default 'News',
  featured_image_url text,
  tags text[] not null default '{}'::text[],
  published_at timestamptz,
  view_count integer not null default 0,
  is_published boolean not null default false,
  show_wholesale_cta boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blog_posts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint blog_posts_slug_unique unique (slug),
  constraint blog_posts_view_count_non_negative check (view_count >= 0)
);

comment on table public.blog_posts is
  'Blog and news articles shown on the public site (/news).';
comment on column public.blog_posts.slug is
  'URL segment for /news/[slug] (lowercase kebab-case).';
comment on column public.blog_posts.excerpt is
  'Lead summary shown below the title on the detail page and in listing cards.';
comment on column public.blog_posts.content is
  'Article body HTML rendered inside the prose container.';
comment on column public.blog_posts.category is
  'Badge label shown on listing and detail pages (e.g. News).';
comment on column public.blog_posts.tags is
  'Hashtags or topic labels for the article.';
comment on column public.blog_posts.show_wholesale_cta is
  'Whether to show the wholesale registration CTA block at the bottom of the article.';

create index blog_posts_published_idx
  on public.blog_posts (is_published, published_at desc, id desc);

create index blog_posts_category_published_idx
  on public.blog_posts (category, is_published, published_at desc);

create trigger blog_posts_set_updated_at
  before update on public.blog_posts
  for each row
  execute function public.set_updated_at();

-- Curated "Related Posts" links between articles.
create table public.blog_post_related (
  post_id bigint not null references public.blog_posts (id) on delete cascade,
  related_post_id bigint not null references public.blog_posts (id) on delete cascade,
  sort_order integer not null default 0,
  primary key (post_id, related_post_id),
  constraint blog_post_related_not_self check (post_id <> related_post_id)
);

comment on table public.blog_post_related is
  'Manually ordered related-article links shown at the bottom of a blog post.';

create index blog_post_related_post_id_sort_order_idx
  on public.blog_post_related (post_id, sort_order, related_post_id);

-- Increment view count from the public detail page without exposing direct updates.
create or replace function public.increment_blog_post_view_count(p_slug text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.blog_posts
  set view_count = view_count + 1
  where slug = p_slug
    and is_published = true
    and (published_at is null or published_at <= now());
end;
$$;

comment on function public.increment_blog_post_view_count(text) is
  'Atomically increments view_count for a published blog post by slug.';

alter table public.blog_posts enable row level security;
alter table public.blog_post_related enable row level security;

create policy "Anyone can read published blog posts"
  on public.blog_posts
  for select
  to anon, authenticated
  using (
    is_published = true
    and (published_at is null or published_at <= now())
  );

create policy "Anyone can read related posts for published articles"
  on public.blog_post_related
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.blog_posts bp
      where bp.id = blog_post_related.post_id
        and bp.is_published = true
        and (bp.published_at is null or bp.published_at <= now())
    )
    and exists (
      select 1
      from public.blog_posts bp
      where bp.id = blog_post_related.related_post_id
        and bp.is_published = true
        and (bp.published_at is null or bp.published_at <= now())
    )
  );

grant select on public.blog_posts to anon, authenticated;
grant insert, update, delete on public.blog_posts to authenticated;
grant all on public.blog_posts to service_role;

grant select on public.blog_post_related to anon, authenticated;
grant insert, update, delete on public.blog_post_related to authenticated;
grant all on public.blog_post_related to service_role;

grant execute on function public.increment_blog_post_view_count(text) to anon, authenticated;

-- Admin CRUD
create policy "Admins can read all blog posts"
  on public.blog_posts
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert blog posts"
  on public.blog_posts
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update blog posts"
  on public.blog_posts
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete blog posts"
  on public.blog_posts
  for delete
  to authenticated
  using (public.is_admin());

create policy "Admins can read all blog post relations"
  on public.blog_post_related
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert blog post relations"
  on public.blog_post_related
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update blog post relations"
  on public.blog_post_related
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete blog post relations"
  on public.blog_post_related
  for delete
  to authenticated
  using (public.is_admin());

-- Seed from Home.tsx news carousel (messages/en.json → news.items).
insert into public.blog_posts (
  slug,
  title,
  excerpt,
  content,
  category,
  featured_image_url,
  tags,
  published_at,
  view_count,
  is_published,
  show_wholesale_cta
)
values
  (
    'how-it-all-began-opening-first-store-north-hobart',
    'How It All Began: Opening Our First Store at 335 Elizabeth St, North Hobart',
    'In 2016, Dr. Tien had one dream — to bring the authentic flavours of Vietnamese street food to Tasmania. Starting from a small shopfront at 335 Elizabeth Street, North Hobart, he wanted every Hobartian to experience the warmth of Vietnamese culture through fresh, healthy, and affordable food. That first store became the heart of what Saigon Express is today.',
    '<p>In 2016, Dr. Tien had one dream — to bring the authentic flavours of Vietnamese street food to Tasmania. Starting from a small shopfront at 335 Elizabeth Street, North Hobart, he wanted every Hobartian to experience the warmth of Vietnamese culture through fresh, healthy, and affordable food. That first store became the heart of what Saigon Express is today.</p>',
    'OUR STORY',
    '/manus-storage/news-story-began_47dbdf79.jpg',
    '{}'::text[],
    '2016-06-01T00:00:00.000Z'::timestamptz,
    142,
    true,
    false
  ),
  (
    'the-people-behind-every-bowl-saigon-express-family',
    'The People Behind Every Bowl: Meet the Saigon Express Family',
    'Behind every steaming bowl of pho and every freshly baked bánh mì is a dedicated team who treat every customer like family. Our staff bring passion, culture, and care to every single dish — every single day.',
    '<p>Behind every steaming bowl of pho and every freshly baked bánh mì is a dedicated team who treat every customer like family. Our staff bring passion, culture, and care to every single dish — every single day.</p>',
    'TEAM',
    '/manus-storage/news-team-behind_03530abb.jpg',
    '{}'::text[],
    '2024-03-15T00:00:00.000Z'::timestamptz,
    87,
    true,
    false
  ),
  (
    'saigon-express-sorell-8th-store-open',
    'Saigon Express Sorell — Our 8th Store Is Now Open!',
    'We''re thrilled to announce the opening of Saigon Express Sorell, our 8th store in Tasmania! Bringing fresh, healthy Vietnamese food to the Sorell community — because great food should be accessible to everyone across the island.',
    '<p>We''re thrilled to announce the opening of Saigon Express Sorell, our 8th store in Tasmania! Bringing fresh, healthy Vietnamese food to the Sorell community — because great food should be accessible to everyone across the island.</p>',
    'NEW STORE',
    '/manus-storage/sorell_store_food_36779d67.jpg',
    array['Sorell', 'NewStore']::text[],
    '2025-04-10T00:00:00.000Z'::timestamptz,
    203,
    true,
    false
  )
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  category = excluded.category,
  featured_image_url = excluded.featured_image_url,
  tags = excluded.tags,
  published_at = excluded.published_at,
  view_count = excluded.view_count,
  is_published = excluded.is_published,
  show_wholesale_cta = excluded.show_wholesale_cta,
  updated_at = now();

-- Related posts: newest article links to the other two home-page stories.
insert into public.blog_post_related (post_id, related_post_id, sort_order)
select
  main_post.id,
  related_post.id,
  related.sort_order
from public.blog_posts main_post
cross join (
  values
    ('the-people-behind-every-bowl-saigon-express-family', 1),
    ('how-it-all-began-opening-first-store-north-hobart', 2)
) as related (slug, sort_order)
join public.blog_posts related_post on related_post.slug = related.slug
where main_post.slug = 'saigon-express-sorell-8th-store-open'
on conflict (post_id, related_post_id) do update set
  sort_order = excluded.sort_order;
