-- Product customisation groups and options (replaces hard-coded ItemCustomiseModal rules).
-- Categories and products reference groups by ordered bigint[] ids; product ids win over category.
-- When products.customizations_disabled is true, no customisations are shown for that product.
create type public.product_customization_type as enum ('single', 'multi');

grant usage on type public.product_customization_type to anon, authenticated, service_role;

create table public.product_customizations (
  id bigint generated by default as identity primary key,
  kind public.category_kind not null default 'menu',
  key text not null,
  title text not null,
  type public.product_customization_type not null,
  required boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_customizations_kind_key_unique unique (kind, key),
  constraint product_customizations_key_format check (key ~ '^[a-z][a-z0-9_]*$')
);

comment on table public.product_customizations is
  'Customisation groups for products (e.g. protein choice, spice level). Referenced by categories and products.';
comment on column public.product_customizations.kind is
  'Sales channel this group belongs to: menu, catering, or wholesale.';
comment on column public.product_customizations.key is
  'Stable identifier used in cart selections and admin tooling (e.g. protein_banh_mi, spice).';
comment on column public.product_customizations.title is
  'Display title for the customisation group.';
comment on column public.product_customizations.type is
  'single = pick one option; multi = pick any number.';
comment on column public.product_customizations.required is
  'When true, the customer must select at least one option before adding to cart.';
comment on column public.product_customizations.sort_order is
  'Default ordering when building admin lists; category/product arrays control runtime order.';

create table public.product_customization_options (
  id bigint generated by default as identity primary key,
  customization_id bigint not null references public.product_customizations (id) on delete cascade,
  key text not null,
  title text not null,
  price numeric(10, 2) not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_customization_options_customization_key_unique unique (customization_id, key),
  constraint product_customization_options_key_format check (key ~ '^[a-z][a-z0-9_]*$'),
  constraint product_customization_options_price_nonneg check (price >= 0)
);

comment on table public.product_customization_options is
  'Selectable options within a product customisation group.';
comment on column public.product_customization_options.key is
  'Stable identifier stored in cart selections (e.g. pork, extra_beef).';
comment on column public.product_customization_options.title is
  'Display label for the option.';
comment on column public.product_customization_options.price is
  'Additional charge in AUD when this option is selected.';

create index product_customizations_kind_sort_idx
  on public.product_customizations (kind, sort_order, id);

create index product_customization_options_customization_id_idx
  on public.product_customization_options (customization_id, sort_order, id);

create trigger product_customizations_set_updated_at
  before update on public.product_customizations
  for each row
  execute function public.set_updated_at();

create trigger product_customization_options_set_updated_at
  before update on public.product_customization_options
  for each row
  execute function public.set_updated_at();

alter table public.products
  add column customization_ids bigint[] not null default '{}'::bigint[],
  add column customizations_disabled boolean not null default false;

comment on column public.products.customization_ids is
  'When non-empty, overrides category customisation_ids for this product (same ordering semantics).';
comment on column public.products.customizations_disabled is
  'When true, this product shows no customisations even if category or product ids are set.';

alter table public.product_customizations enable row level security;
alter table public.product_customization_options enable row level security;

create policy "Anyone can read product customizations"
  on public.product_customizations
  for select
  to anon, authenticated
  using (true);

create policy "Anyone can read product customization options"
  on public.product_customization_options
  for select
  to anon, authenticated
  using (true);

create policy "Admins can read all product customizations"
  on public.product_customizations
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert product customizations"
  on public.product_customizations
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update product customizations"
  on public.product_customizations
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete product customizations"
  on public.product_customizations
  for delete
  to authenticated
  using (public.is_admin());

create policy "Admins can read all product customization options"
  on public.product_customization_options
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert product customization options"
  on public.product_customization_options
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update product customization options"
  on public.product_customization_options
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete product customization options"
  on public.product_customization_options
  for delete
  to authenticated
  using (public.is_admin());

grant select on public.product_customizations to anon, authenticated;
grant insert, update, delete on public.product_customizations to authenticated;
grant all on public.product_customizations to service_role;

grant select on public.product_customization_options to anon, authenticated;
grant insert, update, delete on public.product_customization_options to authenticated;
grant all on public.product_customization_options to service_role;

-- ---------------------------------------------------------------------------
-- Seed groups (from ItemCustomiseModal groupTitles + category rules)
-- ---------------------------------------------------------------------------

insert into public.product_customizations (
  id,
  kind,
  key,
  title,
  type,
  required,
  sort_order
)
overriding system value
values
  (1, 'menu', 'protein_banh_mi', 'Choose Your Protein', 'single', true, 10),
  (2, 'menu', 'protein_rice', 'Protein Choice', 'single', false, 20),
  (3, 'menu', 'extras', 'Add Extras', 'multi', false, 30),
  (4, 'menu', 'veggies', 'Veggies & Toppings', 'multi', false, 40),
  (5, 'menu', 'spice', 'Spice Level', 'single', true, 50),
  (6, 'menu', 'spice_optional', 'Spice Level', 'single', false, 60),
  (7, 'menu', 'sauce_banh_mi', 'Sauce', 'multi', false, 70),
  (8, 'menu', 'sauce_condiments', 'Condiments', 'multi', false, 80)
on conflict (kind, key) do update set
  title = excluded.title,
  type = excluded.type,
  required = excluded.required,
  sort_order = excluded.sort_order;

select setval(
  pg_get_serial_sequence('public.product_customizations', 'id'),
  (select coalesce(max(id), 1) from public.product_customizations)
);

-- Protein options (shared by protein_banh_mi and protein_rice)
insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (1, 'pork', 'BBQ Pork (Xá Xíu)', 0, 10),
  (1, 'chicken', 'Grilled Chicken', 0, 20),
  (1, 'prawn', 'Prawn', 1.50, 30),
  (1, 'beef', 'Beef (Bò)', 1.50, 40),
  (1, 'tofu', 'Tofu (Vegetarian)', 0, 50),
  (1, 'pork_belly', 'Crackling Pork Belly', 2.00, 60),
  (1, 'mixed', 'Mixed Proteins', 1.00, 70),
  (2, 'pork', 'BBQ Pork (Xá Xíu)', 0, 10),
  (2, 'chicken', 'Grilled Chicken', 0, 20),
  (2, 'prawn', 'Prawn', 1.50, 30),
  (2, 'beef', 'Beef (Bò)', 1.50, 40),
  (2, 'tofu', 'Tofu (Vegetarian)', 0, 50),
  (2, 'pork_belly', 'Crackling Pork Belly', 2.00, 60),
  (2, 'mixed', 'Mixed Proteins', 1.00, 70)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- Extras
insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (3, 'extra_beef', 'Extra Beef', 3.00, 10),
  (3, 'extra_chicken', 'Extra Chicken', 3.00, 20),
  (3, 'extra_prawn', 'Extra Prawn', 3.00, 30),
  (3, 'extra_seafood', 'Extra Seafood', 5.00, 40),
  (3, 'extra_crispy_pork', 'Extra Crispy Pork', 5.00, 50),
  (3, 'extra_veggies', 'Extra Veggies', 3.00, 60),
  (3, 'extra_noodles', 'Extra Noodles', 2.00, 70),
  (3, 'extra_fried_egg', 'Extra Fried Egg', 2.50, 80),
  (3, 'extra_broth', 'Extra Broth', 2.00, 90),
  (3, 'extra_chilli', 'Extra Chilli', 1.00, 100),
  (3, 'extra_sauce', 'Extra Sauce', 2.00, 110)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- Bánh mì veggies
insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (4, 'no_coriander', 'No Coriander', 0, 10),
  (4, 'no_spring_onion', 'No Spring Onion', 0, 20),
  (4, 'no_daikon', 'No Daikon & Carrot', 0, 30),
  (4, 'no_cucumber', 'No Cucumber', 0, 40),
  (4, 'extra_veggies', 'Extra Veggies', 0, 50),
  (4, 'extra_coriander', 'Extra Coriander', 0, 60),
  (4, 'extra_cucumber', 'Extra Cucumber', 0, 70),
  (4, 'no_veggies', 'No Veggies at All', 0, 80)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- Spice (required)
insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (5, 'no_chilli', 'No Chilli', 0, 10),
  (5, 'mild', 'Mild', 0, 20),
  (5, 'medium', 'Medium', 0, 30),
  (5, 'hot', 'Hot 🌶️', 0, 40),
  (5, 'extra_hot', 'Extra Hot 🌶️🌶️', 0, 50)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- Spice (optional) — same options, not required before add-to-cart
insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (6, 'no_chilli', 'No Chilli', 0, 10),
  (6, 'mild', 'Mild', 0, 20),
  (6, 'medium', 'Medium', 0, 30),
  (6, 'hot', 'Hot 🌶️', 0, 40),
  (6, 'extra_hot', 'Extra Hot 🌶️🌶️', 0, 50)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- Sauce / condiments (same option set, different group titles)
insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (7, 'sauce_mayo', 'Sriracha Mayo', 1.00, 10),
  (7, 'sauce_hoisin', 'Hoisin Sauce', 1.00, 20),
  (7, 'sauce_fish', 'Fish Sauce Dressing', 1.00, 30),
  (7, 'sauce_soy', 'Soy Sauce', 1.00, 40),
  (7, 'sauce_chilli', 'Chilli Sauce', 1.00, 50),
  (7, 'no_sauce', 'No Sauce', 0, 60),
  (8, 'sauce_mayo', 'Sriracha Mayo', 1.00, 10),
  (8, 'sauce_hoisin', 'Hoisin Sauce', 1.00, 20),
  (8, 'sauce_fish', 'Fish Sauce Dressing', 1.00, 30),
  (8, 'sauce_soy', 'Soy Sauce', 1.00, 40),
  (8, 'sauce_chilli', 'Chilli Sauce', 1.00, 50),
  (8, 'no_sauce', 'No Sauce', 0, 60)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- BEGIN catering customizations (generated by scripts/generate-chaocatering-seed.mjs)

insert into public.product_customizations (
  id,
  kind,
  key,
  title,
  type,
  required,
  sort_order
)
overriding system value
values
  (9, 'catering', 'ct_warm_me_up_1', 'My noodle:', 'single', true, 10),
  (10, 'catering', 'ct_warm_me_up_2', 'Fresh rice paper roll:', 'single', true, 20),
  (11, 'catering', 'ct_warm_me_up_3', 'Spring rolls:', 'single', true, 30),
  (12, 'catering', 'ct_chaos_signature_1', 'Homemade crispy spring rolls (10 pcs)', 'single', true, 10),
  (13, 'catering', 'ct_chaos_signature_2', 'Fresh rice paper rolls (10 pcs)', 'single', true, 20),
  (14, 'catering', 'ct_chaos_signature_3', 'Vermicelli bowls (10 bowls)', 'single', true, 30),
  (15, 'catering', 'ct_noodle_soup_combo_1', 'Signature Pho (10 bowls)', 'single', true, 10),
  (16, 'catering', 'ct_noodle_soup_combo_2', 'Homemade crispy spring rolls (10 pcs)', 'single', true, 20),
  (17, 'catering', 'ct_light_and_easy_1', 'Fresh rice paper rolls (5 pcs)', 'single', true, 10),
  (18, 'catering', 'ct_floral_rolls_1_1', 'My platter:', 'single', true, 10),
  (19, 'catering', 'ct_vietnamese_salads_1', 'My salad platter:', 'single', true, 10),
  (20, 'catering', 'ct_signature_salt_pepper_1', 'My favourite platter:', 'single', true, 10),
  (21, 'catering', 'ct_classic_fried_rice_1', 'My favourite platter:', 'single', true, 10),
  (22, 'catering', 'ct_signature_pho_1', 'Pho noodle soup:', 'single', true, 10),
  (23, 'catering', 'ct_signature_pho_2', 'Bao bun:', 'single', true, 20),
  (24, 'catering', 'ct_signature_pho_3', 'Favourite dessert', 'single', true, 30),
  (25, 'catering', 'ct_taste_of_vietnam_1', 'Vermicelli bowl', 'single', true, 10),
  (26, 'catering', 'ct_shaking_fillets_with_rice_1', 'My favourite:', 'single', true, 10),
  (27, 'catering', 'ct_fried_rice_combo_1', 'Fried rice:', 'single', true, 10),
  (28, 'catering', 'ct_fried_rice_combo_2', 'Bao bun:', 'single', true, 20),
  (29, 'catering', 'ct_vermicelli_combo_1', 'Vermicelli noodle salad:', 'single', true, 10),
  (30, 'catering', 'ct_vermicelli_combo_2', 'Vietnamese crispy spring roll', 'single', true, 20),
  (31, 'catering', 'ct_deluxe_mixed_box_1', 'Favourite dessert:', 'single', true, 10),
  (32, 'catering', 'ct_roll_combo_1', 'Vietnamese crispy spring rolls:', 'single', true, 10),
  (33, 'catering', 'ct_roll_combo_2', 'Fresh rice paper rolls:', 'single', true, 20),
  (34, 'catering', 'ct_simply_delicious_1', 'Fresh rice paper roll', 'single', true, 10),
  (35, 'catering', 'ct_simply_delicious_2', 'Popular Bao Bun', 'single', true, 20),
  (36, 'catering', 'ct_simply_delicious_3', 'Satay skewer', 'single', true, 30),
  (37, 'catering', 'ct_nice_and_easy_1', 'Vermicelli bowl', 'single', true, 10),
  (38, 'catering', 'ct_nice_and_easy_2', 'Fresh rice paper roll', 'single', true, 20),
  (39, 'catering', 'ct_nice_and_easy_3', 'Popular Bao Bun', 'single', true, 30),
  (40, 'catering', 'ct_peace_harmony_1', 'Classic fried rice', 'single', true, 10),
  (41, 'catering', 'ct_peace_harmony_2', 'Homemade crispy spring roll', 'single', true, 20),
  (42, 'catering', 'ct_peace_harmony_3', 'Popular Bao Bun', 'single', true, 30),
  (43, 'catering', 'ct_the_divine_1', 'Vermicelli bowl', 'single', true, 10),
  (44, 'catering', 'ct_the_divine_2', 'Popular Bao Bun', 'single', true, 20),
  (45, 'catering', 'ct_the_divine_3', 'One of your favourite desserts', 'single', true, 30),
  (46, 'catering', 'ct_fresh_rice_paper_rolls_1', 'My platter:', 'single', true, 10),
  (47, 'catering', 'ct_homemade_crispy_spring_rolls_1', 'My platter:', 'single', true, 10),
  (48, 'catering', 'ct_popular_bao_buns_1', 'My favourite:', 'single', true, 10),
  (49, 'catering', 'ct_sizzling_skewers_1', 'My platter:', 'single', true, 10),
  (50, 'catering', 'ct_fresh_rice_paper_rolls_add_on_1', 'My favourite rolls:', 'single', true, 10),
  (51, 'catering', 'ct_popular_bao_buns_ind_1', 'My favourite buns:', 'single', true, 10),
  (52, 'catering', 'ct_homemade_crispy_spring_rolls_ind_1', 'My favourite spring rolls:', 'single', true, 10),
  (53, 'catering', 'ct_sizzling_skewers_ind_1', 'My favourite skewers:', 'single', true, 10),
  (54, 'catering', 'ct_floral_rolls_add_on_1', 'My favourite rolls:', 'single', true, 10),
  (55, 'catering', 'ct_signature_salt_pepper_ind_1', 'My favourite dishes:', 'single', true, 10),
  (56, 'catering', 'ct_classic_fried_rice_ind_1', 'My favourite one:', 'single', true, 10),
  (57, 'catering', 'ct_signature_noodle_soup_add_on_1', 'My favourite noodles:', 'single', true, 10),
  (58, 'catering', 'ct_vermicelli_noodle_add_on_1', 'My favourite noodles:', 'single', true, 10),
  (59, 'catering', 'ct_vietnamese_salad_add_on_1', 'My favourite salads:', 'single', true, 10),
  (60, 'catering', 'ct_soft_drinks_1', 'My favourite one:', 'single', true, 10),
  (61, 'catering', 'ct_nudie_fruit_juices_1', 'My favourite one:', 'single', true, 10)
on conflict (kind, key) do update set
  title = excluded.title,
  type = excluded.type,
  required = excluded.required,
  sort_order = excluded.sort_order;

insert into public.product_customization_options (
  customization_id,
  key,
  title,
  price,
  sort_order
)
values
  (9, 'wagyu', 'Wagyu', 0.00, 10),
  (9, 'chicken', 'Chicken', 0.00, 20),
  (9, 'tofu', 'Tofu', 0.00, 30),
  (10, 'tiger_prawn_lean_pork', 'Tiger Prawn & Lean Pork', 0.00, 10),
  (10, 'lemongrass_chicken', 'Lemongrass Chicken', 0.00, 20),
  (10, 'tofu_v', 'Tofu (V)', 0.00, 30),
  (11, 'minced_pork', 'Minced pork', 0.00, 10),
  (11, 'taro_veg_v', 'Taro & veg (V)', 0.00, 20),
  (12, 'minced_pork', 'Minced pork', 0.00, 10),
  (12, 'taro_vegetables_v', 'Taro & vegetables (V)', 0.00, 20),
  (13, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 10),
  (13, 'prawn_pork', 'Prawn & pork', 0.00, 20),
  (13, 'tofu_v', 'Tofu (V)', 0.00, 30),
  (14, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 10),
  (14, 'grilled_pork_spring_rolls', 'Grilled pork & spring rolls', 0.00, 20),
  (14, 'lemongrass_tofu_vegetable_spring_rolls_v', 'Lemongrass tofu & vegetable spring rolls (V)', 0.00, 30),
  (15, 'wagyu_beef', 'Wagyu beef', 0.00, 10),
  (15, 'shredded_chicken_breast', 'Shredded chicken breast', 0.00, 20),
  (15, 'golden_tofu_and_seasonal_vegetables_v', 'Golden tofu and seasonal vegetables (V)', 0.00, 30),
  (16, 'minced_pork', 'Minced pork', 0.00, 10),
  (16, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (17, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 10),
  (17, 'prawn_pork', 'Prawn & pork', 0.00, 20),
  (17, 'tofu_v', 'Tofu (V)', 0.00, 30),
  (18, 'x_10_x_black_charcoal_rolls_with_roasted', '10 x Black charcoal rolls with roasted duck & cucumber', 0.00, 10),
  (18, 'x_10_x_pink_beetroot_rolls_with_seared_s', '10 x Pink beetroot rolls with seared salmon & green apple', 0.00, 20),
  (18, 'x_10_x_yellow_turmeric_rolls_with_chicke', '10 x Yellow turmeric rolls with chicken & avocado', 0.00, 30),
  (18, 'x_10_x_yellow_turmeric_rolls_with_tofu_a', '10 x Yellow turmeric rolls with tofu & avocado (V)', 0.00, 40),
  (19, 'tender_sliced_beef_green_mango_or_green', 'Tender sliced beef & green mango or green apple salad', 0.00, 10),
  (19, 'free_range_chicken_thinly_sliced_mixed_c', 'Free-range chicken & thinly sliced mixed cabbages salad', 0.00, 20),
  (19, 'tiger_prawn_pork_with_green_papaya_salad', 'Tiger prawn & pork with green papaya salad', 0.00, 30),
  (19, 'crispy_tofu_green_papaya_salad_v', 'Crispy tofu & green papaya salad (V)', 0.00, 40),
  (20, 'calamari', 'Calamari', 0.00, 10),
  (20, 'eggplant_v', 'Eggplant (V)', 0.00, 20),
  (20, 'tofu_v', 'Tofu (V)', 0.00, 30),
  (21, 'meat_seafood_combination', 'Meat & seafood combination', 0.00, 10),
  (21, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (22, 'wagyu_beef', 'Wagyu beef', 0.00, 10),
  (22, 'chicken', 'Chicken', 0.00, 20),
  (22, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 30),
  (23, 'crispy_pork_belly', 'Crispy pork belly', 0.00, 10),
  (23, 'tempura_eggplant_v', 'Tempura eggplant (V)', 0.00, 20),
  (24, 'volcano_choc_pudding', 'Volcano choc pudding', 0.00, 10),
  (24, 'creamy_cheesecake', 'Creamy cheesecake', 0.00, 20),
  (25, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 10),
  (25, 'grilled_pork_spring_rolls', 'Grilled pork & spring rolls', 0.00, 20),
  (26, 'beef', 'Beef', 0.00, 10),
  (26, 'chicken', 'Chicken', 0.00, 20),
  (26, 'tofu_v', 'Tofu (V)', 0.00, 30),
  (27, 'meat_combination', 'Meat combination', 0.00, 10),
  (27, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (28, 'crispy_pork_belly', 'Crispy pork belly', 0.00, 10),
  (28, 'tempura_eggplant_v', 'Tempura eggplant (V)', 0.00, 20),
  (29, 'honey_grilled_pork', 'Honey grilled pork', 0.00, 10),
  (29, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (29, 'lemongrass_tofu_v', 'Lemongrass tofu (V)', 0.00, 30),
  (30, 'minced_pork', 'Minced pork', 0.00, 10),
  (30, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (31, 'volcano_choc_pudding', 'Volcano choc pudding', 0.00, 10),
  (31, 'creamy_cheesecake', 'Creamy cheesecake', 0.00, 20),
  (32, 'minced_pork', 'Minced pork', 0.00, 10),
  (32, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (33, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 10),
  (33, 'tofu_v', 'Tofu (V)', 0.00, 20),
  (34, 'prawn_pork', 'Prawn & pork', 0.00, 10),
  (34, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (34, 'tofu', 'Tofu', 0.00, 30),
  (35, 'white_buns_with_crispy_pork_belly', 'White buns with crispy pork belly', 0.00, 10),
  (35, 'white_buns_with_tempura_eggplant_v', 'White buns with tempura eggplant (V)', 0.00, 20),
  (36, 'satay_chicken', 'Satay chicken', 0.00, 10),
  (36, 'sizzling_wagyu_beef_cube', 'Sizzling wagyu beef cube', 0.00, 20),
  (36, 'silken_tofu_vegetable_v', 'Silken tofu & vegetable (V)', 0.00, 30),
  (37, 'grilled_pork_spring_rolls', 'Grilled pork & spring rolls', 0.00, 10),
  (37, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (37, 'lemongrass_tofu_vegetable_spring_rolls_v', 'Lemongrass tofu & vegetable spring rolls (V)', 0.00, 30),
  (38, 'prawn_pork', 'Prawn & pork', 0.00, 10),
  (38, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (38, 'tofu', 'Tofu', 0.00, 30),
  (39, 'white_buns_with_crispy_pork_belly', 'White buns with crispy pork belly', 0.00, 10),
  (39, 'white_buns_with_tempura_eggplant_v', 'White buns with tempura eggplant (V)', 0.00, 20),
  (40, 'meat_seafood_combination', 'Meat & seafood combination', 0.00, 10),
  (40, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (41, 'minced_pork', 'Minced pork', 0.00, 10),
  (41, 'taro_vegetables_v', 'Taro & vegetables (V)', 0.00, 20),
  (42, 'white_buns_with_crispy_pork_belly', 'White buns with crispy pork belly', 0.00, 10),
  (42, 'white_buns_with_tempura_eggplant_v', 'White buns with tempura eggplant (V)', 0.00, 20),
  (43, 'grilled_pork_spring_rolls', 'Grilled pork & spring rolls', 0.00, 10),
  (43, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (43, 'lemongrass_tofu_vegetable_spring_rolls_v', 'Lemongrass tofu & vegetable spring rolls (V)', 0.00, 30),
  (44, 'white_buns_with_crispy_pork_belly', 'White buns with crispy pork belly', 0.00, 10),
  (44, 'white_buns_with_tempura_eggplant_v', 'White buns with tempura eggplant (V)', 0.00, 20),
  (45, 'volcano_choc_pudding', 'Volcano choc pudding', 0.00, 10),
  (45, 'creamy_cheesecake', 'Creamy cheesecake', 0.00, 20),
  (46, 'x_10_x_prawn_lean_pork', '10 x Prawn & Lean pork', 0.00, 10),
  (46, 'x_10_x_lemongrass_chicken', '10 x Lemongrass chicken', 0.00, 20),
  (46, 'x_10_x_honey_grilled_pork', '10 x Honey grilled pork', 0.00, 30),
  (46, 'x_10_x_tofu_v', '10 x Tofu (V)', 0.00, 40),
  (47, 'x_10_x_minced_pork', '10 x Minced pork', 0.00, 10),
  (47, 'x_10_x_taro_vegetables_v', '10 x Taro & vegetables (V)', 0.00, 20),
  (48, 'x_10_x_white_buns_with_crispy_pork_belly', '10 x White buns with crispy pork belly', 0.00, 10),
  (48, 'x_10_x_white_buns_with_tempura_eggplant_', '10 x White buns with tempura eggplant (V)', 0.00, 20),
  (48, 'x_10_x_white_buns_with_crispy_tofu_v', '10 x White buns with crispy tofu (V)', 0.00, 30),
  (49, 'x_10_x_satay_chicken', '10 x Satay chicken', 0.00, 10),
  (49, 'x_10_x_sizzling_wagyu_beef_cube', '10 x Sizzling wagyu beef cube', 0.00, 20),
  (49, 'x_10_x_silken_tofu_vegetable_v', '10 x Silken tofu & vegetable (V)', 0.00, 30),
  (50, 'tiger_prawn_pork', 'Tiger prawn & pork', 0.00, 10),
  (50, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (50, 'honey_grilled_pork', 'Honey grilled pork', 0.00, 30),
  (50, 'tofu_salad_v', 'Tofu & salad (V)', 0.00, 40),
  (51, 'crispy_pork_belly', 'Crispy pork belly', 0.00, 10),
  (51, 'crispy_eggplant_v', 'Crispy eggplant (V)', 0.00, 20),
  (52, 'minced_pork_carrot_taro_mushroom_mung_be', 'Minced pork, carrot, taro, mushroom & mung bean noodle', 0.00, 10),
  (52, 'carrot_taro_mushroom_mung_bean_noodle_v', 'Carrot, taro, mushroom & mung bean noodle (V)', 0.00, 20),
  (53, 'satay_chicken', 'Satay chicken', 0.00, 10),
  (53, 'sizzling_wagyu_beef', 'Sizzling wagyu beef', 0.00, 20),
  (53, 'silken_tofu_vegetables_v', 'Silken tofu & vegetables (V)', 0.00, 30),
  (54, 'black_charcoal_rolls_with_roasted_duck_c', 'Black charcoal rolls with roasted duck & cucumber', 0.00, 10),
  (54, 'pink_beetroot_rolls_with_seared_salmon_g', 'Pink beetroot rolls with seared salmon & green apple', 0.00, 20),
  (54, 'yellow_turmeric_rolls_with_chicken_avoca', 'Yellow turmeric rolls with chicken & avocado', 0.00, 30),
  (54, 'yellow_turmeric_rolls_with_tofu_x_avocad', 'Yellow turmeric rolls with tofu x avocado (V)', 0.00, 40),
  (55, 'calamari', 'Calamari', 0.00, 10),
  (55, 'eggplant_v', 'Eggplant (V)', 0.00, 20),
  (55, 'tofu_v', 'Tofu (V)', 0.00, 30),
  (56, 'meat_seafood_combination', 'Meat & seafood combination', 0.00, 10),
  (56, 'tofu_vegetables_v', 'Tofu & vegetables (V)', 0.00, 20),
  (57, 'wagyu_beef', 'Wagyu beef', 0.00, 10),
  (57, 'shredded_chicken_breast', 'Shredded chicken breast', 0.00, 20),
  (57, 'golden_tofu_and_seasonal_vegetables_v', 'Golden tofu and seasonal vegetables (V)', 0.00, 30),
  (58, 'grilled_pork_pork_spring_rolls', 'Grilled pork & pork spring rolls', 0.00, 10),
  (58, 'lemongrass_chicken', 'Lemongrass chicken', 0.00, 20),
  (58, 'lemongrass_beef', 'Lemongrass beef', 0.00, 30),
  (58, 'lemongrass_tofu_vegetable_spring_rolls_v', 'Lemongrass tofu & vegetable spring rolls (V)', 0.00, 40),
  (59, 'tender_sliced_beef_green_mango_green_app', 'Tender sliced beef & green mango / green apple', 0.00, 10),
  (59, 'free_range_chicken_mixed_cabbages', 'Free-range chicken & mixed cabbages', 0.00, 20),
  (59, 'tiger_prawn_pork_with_green_papaya_salad', 'Tiger prawn & pork with green papaya salad', 0.00, 30),
  (59, 'crispy_tofu_green_papaya_v', 'Crispy tofu & green papaya (V)', 0.00, 40),
  (60, 'coke', 'Coke', 0.00, 10),
  (60, 'diet_coke', 'Diet Coke', 0.00, 20),
  (60, 'coke_zero', 'Coke Zero', 0.00, 30),
  (60, 'sprite', 'Sprite', 0.00, 40),
  (61, 'fresh_apple_juice', 'Fresh apple juice', 0.00, 10),
  (61, 'fresh_orange_juice', 'Fresh orange juice', 0.00, 20)
on conflict (customization_id, key) do update set
  title = excluded.title,
  price = excluded.price,
  sort_order = excluded.sort_order;

select setval(
  pg_get_serial_sequence('public.product_customizations', 'id'),
  (select coalesce(max(id), 1) from public.product_customizations)
);

-- END catering customizations

-- Link catering products → customization groups
update public.products
set customization_ids = '{}'::bigint[]
where id = 610001 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610002 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610003 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[9, 10, 11]::bigint[]
where id = 610004 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[12, 13, 14]::bigint[]
where id = 610005 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[15, 16]::bigint[]
where id = 610006 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[17]::bigint[]
where id = 610007 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610008 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610009 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610010 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610011 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610012 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610013 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[18]::bigint[]
where id = 610014 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[19]::bigint[]
where id = 610015 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[20]::bigint[]
where id = 610016 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610017 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610018 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610019 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610020 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610021 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610022 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[21]::bigint[]
where id = 610023 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610024 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610025 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610026 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[22, 23, 24]::bigint[]
where id = 610027 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[25]::bigint[]
where id = 610028 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610029 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610030 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[26]::bigint[]
where id = 610031 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610032 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610033 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610034 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[27, 28]::bigint[]
where id = 610035 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[29, 30]::bigint[]
where id = 610036 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[31]::bigint[]
where id = 610037 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610038 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[32, 33]::bigint[]
where id = 610039 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610040 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[34, 35, 36]::bigint[]
where id = 610041 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[37, 38, 39]::bigint[]
where id = 610042 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[40, 41, 42]::bigint[]
where id = 610043 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[43, 44, 45]::bigint[]
where id = 610044 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[46]::bigint[]
where id = 610045 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[47]::bigint[]
where id = 610046 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[48]::bigint[]
where id = 610047 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[49]::bigint[]
where id = 610048 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610049 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[50]::bigint[]
where id = 610050 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[51]::bigint[]
where id = 610051 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610052 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610053 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610054 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[52]::bigint[]
where id = 610055 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610056 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610057 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[53]::bigint[]
where id = 610058 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610059 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610060 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610061 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[54]::bigint[]
where id = 610062 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[55]::bigint[]
where id = 610063 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[56]::bigint[]
where id = 610064 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[57]::bigint[]
where id = 610065 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610066 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610067 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[58]::bigint[]
where id = 610068 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[59]::bigint[]
where id = 610069 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610070 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[60]::bigint[]
where id = 610071 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = array[61]::bigint[]
where id = 610072 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610073 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610074 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610075 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610076 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610077 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610078 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610079 and product_type = 'catering'::public.product_type;

update public.products
set customization_ids = '{}'::bigint[]
where id = 610080 and product_type = 'catering'::public.product_type;
