-- Featured customer reviews (public site carousel).

create table public.featured_reviews (
  id bigint primary key,
  reviewer_name text not null,
  reviewer_picture text,
  rating smallint not null,
  review_text text not null,
  location text,  
  is_featured boolean not null default true,
  created_at timestamptz not null default now(),
  constraint featured_reviews_rating_range check (rating >= 1 and rating <= 5)
);

comment on table public.featured_reviews is
  'Customer reviews shown on the public site (e.g. home page carousel).';

create index featured_reviews_is_featured_created_at_idx
  on public.featured_reviews (is_featured, created_at desc);

alter table public.featured_reviews enable row level security;

create policy "Anyone can read featured reviews"
  on public.featured_reviews
  for select
  to anon, authenticated
  using (is_featured = true);

grant select on public.featured_reviews to anon, authenticated;
grant insert, update, delete on public.featured_reviews to authenticated;
grant all on public.featured_reviews to service_role;

-- Admin CRUD
create policy "Admins can read all featured reviews"
  on public.featured_reviews
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert featured reviews"
  on public.featured_reviews
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update featured reviews"
  on public.featured_reviews
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete featured reviews"
  on public.featured_reviews
  for delete
  to authenticated
  using (public.is_admin());

-- Seed from production sample (refs/samples/reviews.json)
insert into public.featured_reviews (
  id,
  reviewer_name,
  rating,
  review_text,
  location,
  is_featured,
  created_at
)
values
  (
    4,
    'David K.',
    5,
    'Great value for money. The mixed entrée platter is perfect for sharing and the spring rolls are crispy and delicious. Service is quick even during the lunch rush. Will definitely be back!',
    'Glenorchy, TAS',
    true,
    '2026-04-29T04:28:53.000Z'::timestamptz
  ),
  (
    5,
    'Emma R.',
    5,
    'I ordered the bún bowl and it was absolutely delicious — light, fresh, and full of flavour. Love that there are healthy options on the menu. The staff were super helpful with my dietary questions too.',
    'Kingston, TAS',
    true,
    '2026-04-29T04:28:53.000Z'::timestamptz
  ),
  (
    6,
    'Michael C.',
    4,
    'Really solid Vietnamese food at a great price. The crackling roasted pork is a must-try — crispy skin, tender meat, and the dipping sauce is amazing. Only reason I am not giving 5 stars is the wait time on busy days.',
    'Moonah, TAS',
    true,
    '2026-04-29T04:28:53.000Z'::timestamptz
  ),
  (
    1,
    'Sarah M.',
    5,
    'Absolutely love Saigon Express! The bánh mì is the best I have had outside of Vietnam. Fresh ingredients, generous portions, and the staff are always so friendly. My go-to lunch spot in Hobart.',
    'Hobart, TAS',
    true,
    '2026-04-29T04:28:52.000Z'::timestamptz
  ),
  (
    2,
    'James T.',
    5,
    'The pho here is incredible — rich, deeply flavoured broth that warms you right through on a cold Tassie day. I have tried a lot of Vietnamese restaurants and this is genuinely top tier. Highly recommend the combination beef pho.',
    'Sandy Bay, TAS',
    true,
    '2026-04-29T04:28:52.000Z'::timestamptz
  ),
  (
    3,
    'Linh N.',
    5,
    'As a Vietnamese person, I can say this is the real deal. The flavours are authentic and the food reminds me of home. The lemongrass chicken rice is my favourite — perfectly balanced and always fresh.',
    'Launceston, TAS',
    true,
    '2026-04-29T04:28:52.000Z'::timestamptz
  )
on conflict (id) do nothing;

-- North Hobart Google reviews (refs/samples/north-hobart-reviews.json)
-- North Hobart Google reviews (refs/samples/north-hobart-reviews.json)
-- BEGIN north_hobart featured_reviews seed (generated by scripts/upload-featured-review-avatars.mjs)
insert into public.featured_reviews (
  id,
  reviewer_name,
  reviewer_picture,
  rating,
  review_text,
  location,
  is_featured,
  created_at
)
values
  (
    7,
    'Georgia Kett',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/georgia-kett.jpg',
    5,
    'We booked through the First Table app and couldn''t be more impressed. Genuinely one of the best vietnamese restaurants we''ve been to. Great price, great service and it was delishhh. Definitely try their bao buns and fried chicken :) …',
    'North Hobart, TAS',
    true,
    '2026-04-28T12:00:00.000Z'::timestamptz
  ),
  (
    8,
    'Sagar Khatiwada',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/sagar-khatiwada.jpg',
    5,
    'Best in town.

Must try the Crispy roast pork , garlic prown and chicken noodle. …',
    'North Hobart, TAS',
    true,
    '2026-06-14T12:00:00.000Z'::timestamptz
  ),
  (
    9,
    'Stan Wu',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/stan-wu.jpg',
    5,
    'What a fantastic find! The Banh Mi was incredible—the baguette was crispy on the outside and soft inside, filled with flavorful grilled pork and pickled vegetables. We also tried the Bun Cha (grilled pork with noodles) and it was a burst of …',
    'North Hobart, TAS',
    true,
    '2025-11-28T12:00:00.000Z'::timestamptz
  ),
  (
    10,
    'Ando',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/ando.jpg',
    5,
    'One of the best Bahmi''s we have had! The roast duck was one we had to try, and we were not disappointed! The restaurant is clean and the atmosphere is calming, especially thanks to the music. Highly recommend this place. …',
    'North Hobart, TAS',
    true,
    '2025-11-28T12:00:00.000Z'::timestamptz
  ),
  (
    11,
    'Maria Ibegu',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/maria-ibegu.jpg',
    5,
    'We had a good time here celebrating a friend''s birthday.
We enjoyed the seafood fried rice and seafood soup with rice. The kids enjoyed their burgers and the milk shakes in different flavours. …',
    'North Hobart, TAS',
    true,
    '2026-01-28T12:00:00.000Z'::timestamptz
  ),
  (
    12,
    'Scott Tavasci',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/scott-tavasci.jpg',
    5,
    'Suck a great find!
Fast service.
Huge helpings. …',
    'North Hobart, TAS',
    true,
    '2026-04-28T12:00:00.000Z'::timestamptz
  ),
  (
    13,
    'Rupesh Thakur',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/rupesh-thakur.jpg',
    5,
    'I visited Saigon Express in North Hobart about a month ago and had a really good experience. The food was fresh, full of flavour, and came out quickly. The service was friendly and efficient, and the atmosphere was clean and relaxed. …',
    'North Hobart, TAS',
    true,
    '2025-06-28T12:00:00.000Z'::timestamptz
  ),
  (
    14,
    'Andrew d[-_-]b',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/andrew-d-b.jpg',
    5,
    'August 2022: Still serving brilliant Asian Fusion cuisine. Meals are always fresh, delicious and affordable. …',
    'North Hobart, TAS',
    true,
    '2023-06-28T12:00:00.000Z'::timestamptz
  ),
  (
    15,
    'Marine L',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/marine-l.jpg',
    5,
    'Such a nice place! Staff is lovely and food is delicious. We tried the rice noodle salad and the beef pho soup and both were really good! Loved it. …',
    'North Hobart, TAS',
    true,
    '2025-06-28T12:00:00.000Z'::timestamptz
  ),
  (
    16,
    'Maillard Coffee Co',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/maillard-coffee-co.jpg',
    5,
    'Went for Korean Doodles and soups but was told not available on Monday. Was very disappointed but the exceptional customer service impressed me by inviting the kitchen hand to us and talk about what he can do about making something Korean for us 👍 And the food turns out to be my favourite Korean food so far! Overall very worth going.',
    'North Hobart, TAS',
    true,
    '2021-06-28T12:00:00.000Z'::timestamptz
  ),
  (
    17,
    'Jess Mundy',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/jess-mundy.jpg',
    5,
    'Very Good quality food, so many options to choose from on the menu, definitely something for everyone. …',
    'North Hobart, TAS',
    true,
    '2026-02-28T12:00:00.000Z'::timestamptz
  ),
  (
    18,
    'Charles Oreste',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/charles-oreste.jpg',
    5,
    'Food excellent, staff very friendly n helpful . All food eaten 😊

Order type: …',
    'North Hobart, TAS',
    true,
    '2025-11-28T12:00:00.000Z'::timestamptz
  ),
  (
    19,
    'Sean W',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/sean-w.jpg',
    5,
    'Awesome experience. Super yummy food! I recommend this place 100%

Meal type: …',
    'North Hobart, TAS',
    true,
    '2025-07-28T12:00:00.000Z'::timestamptz
  ),
  (
    20,
    'Amelia Hughes',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/amelia-hughes.jpg',
    5,
    'Hands down the best pho I''ve ever had! We had a lovely experience here during our visit to Hobart for Dark Mofo. We had a banh mi (roast duck)/coffee meal deal and the banh mi/pho (chicken) meal deal, both seriously amazing. Warm, friendly and fast service, unbeatable food, awesome sauce on the duck. Thank you!!!',
    'North Hobart, TAS',
    true,
    '2026-06-14T12:00:00.000Z'::timestamptz
  ),
  (
    21,
    'Tom Palfrey',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/tom-palfrey.jpg',
    5,
    'Left a 5-star rating on Google.',
    'North Hobart, TAS',
    true,
    '2026-06-14T12:00:00.000Z'::timestamptz
  )
on conflict (id) do update set
  reviewer_name = excluded.reviewer_name,
  reviewer_picture = excluded.reviewer_picture,
  rating = excluded.rating,
  review_text = excluded.review_text,
  location = excluded.location,
  is_featured = excluded.is_featured,
  created_at = excluded.created_at;
-- END north_hobart featured_reviews seed
-- Hobart Google reviews (refs/samples/hobart-reviews.json)
-- Hobart Google reviews (refs/samples/hobart-reviews.json)
-- BEGIN hobart featured_reviews seed (generated by scripts/upload-featured-review-avatars.mjs)
insert into public.featured_reviews (
  id,
  reviewer_name,
  reviewer_picture,
  rating,
  review_text,
  location,
  is_featured,
  created_at
)
values
  (
    22,
    'Chapman Histology',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/chapman-histology.jpg',
    5,
    'We came a little late (8.15pm) on a Sunday night and ordered Char Kway Teow - it came quickly, was fresh and delicious. The serving size was great, too (I''m a bigger bloke so I was happy). The menu is HUGE, so you''ll need more than one visit to try all the things you like. I highly recommend.',
    'Hobart, TAS',
    true,
    '2026-02-28T12:00:00.000Z'::timestamptz
  ),
  (
    23,
    'Pritesh Duong-Kajaria',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/pritesh-duong-kajaria.jpg',
    5,
    'The vegan options for Banh Mi were par excellence. The tofu and vegetables were packed with flavours - highly recommend Salt and Pepper Tofu and Basil Mushroom and Tofu Banh Mi flavours.',
    'Hobart, TAS',
    true,
    '2026-01-28T12:00:00.000Z'::timestamptz
  ),
  (
    24,
    'TRUE SS',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/true-ss.jpg',
    5,
    'Who''s looking for real Vietnamese food in Hobart city come to thai restaurant it''s so good',
    'Hobart, TAS',
    true,
    '2026-05-28T12:00:00.000Z'::timestamptz
  ),
  (
    25,
    'Pokeeheaven',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/pokeeheaven.jpg',
    5,
    'Like many times before, I ordered from Saigon. Tonight I had tempura prawn bao, chicken avocado rice paper roll and the roast crackling pork..with spices siracha and the other with hoisin. Also the chicken soup. Every single item was …',
    'Hobart, TAS',
    true,
    '2025-12-28T12:00:00.000Z'::timestamptz
  ),
  (
    26,
    'JIM LEE',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/jim-lee.jpg',
    5,
    'One of best Vietnamese restaurant in Hobart, Tasmania. Staffs were very friendly, welcoming and knowing best. Fried spring-rolls were …',
    'Hobart, TAS',
    true,
    '2024-06-28T12:00:00.000Z'::timestamptz
  )
on conflict (id) do update set
  reviewer_name = excluded.reviewer_name,
  reviewer_picture = excluded.reviewer_picture,
  rating = excluded.rating,
  review_text = excluded.review_text,
  location = excluded.location,
  is_featured = excluded.is_featured,
  created_at = excluded.created_at;
-- END hobart featured_reviews seed
-- Sorell Google reviews (refs/samples/sorell-reviews.json)
-- Sorell Google reviews (refs/samples/sorell-reviews.json)
-- BEGIN sorell featured_reviews seed (generated by scripts/upload-featured-review-avatars.mjs)
insert into public.featured_reviews (
  id,
  reviewer_name,
  reviewer_picture,
  rating,
  review_text,
  location,
  is_featured,
  created_at
)
values
  (
    27,
    'John Deliu',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/john-deliu.jpg',
    5,
    'Just had combination rice and char sui Pork rice. Doing rolls were incredible. So flavoursome and perfect flavours. Definitely visit this store ✅✅✅ ⭐️⭐️⭐️⭐️⭐️',
    'Sorell, TAS',
    true,
    '2026-01-28T12:00:00.000Z'::timestamptz
  ),
  (
    28,
    'Regan Tan',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/regan-tan.jpg',
    5,
    'Food is good and has variety and standard for vietnamese cuisine. Prices can be a little more on the affordable scale for town folks. …',
    'Sorell, TAS',
    true,
    '2025-12-28T12:00:00.000Z'::timestamptz
  ),
  (
    29,
    'Kylie Cao',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/kylie-cao.jpg',
    5,
    'We passed by here and had lunch it was so yummy and I love this place definitely should come here 5 stars for all! …',
    'Sorell, TAS',
    true,
    '2025-12-28T12:00:00.000Z'::timestamptz
  ),
  (
    30,
    'Poppy-Rose Harvey',
    'https://gwjwndshezauqvwnbueh.supabase.co/storage/v1/object/public/saigon-express-tasmania/featured-reviews/avatars/poppy-rose-harvey.jpg',
    5,
    'The food tasted excellent and the service was amazing 👏. The staff here are very friendly and kind. And the service was fast and well done. After getting my food in under 5 minutes I was stunned of how fast it was delivered and how yummy …',
    'Sorell, TAS',
    true,
    '2026-01-28T12:00:00.000Z'::timestamptz
  )
on conflict (id) do update set
  reviewer_name = excluded.reviewer_name,
  reviewer_picture = excluded.reviewer_picture,
  rating = excluded.rating,
  review_text = excluded.review_text,
  location = excluded.location,
  is_featured = excluded.is_featured,
  created_at = excluded.created_at;
-- END sorell featured_reviews seed
