-- Franchise Resources Hub: global documents, announcements, and menu training
-- visible to all franchise-privileged members, plus per-member read/completion state.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type public.franchise_resource_type as enum (
  'announcement',
  'document',
  'menu_training'
);

comment on type public.franchise_resource_type is
  'Kind of franchise portal resource shown in the Resources Hub.';

create type public.franchise_resource_taxonomy_place as enum (
  'announcement',
  'document',
  'academy'
);

comment on type public.franchise_resource_taxonomy_place is
  'Place of franchise resource taxonomy (announcement, document, or academy).';

create type public.franchise_resource_taxonomy_kind as enum (
  'folder',
  'category',
  'course',
  'period'
);

comment on type public.franchise_resource_taxonomy_kind is
  'Taxonomy dimension for franchise resources (category, course, or period).';

create type public.franchise_resource_member_status as enum (
  'not_seen',
  'seen',
  'completed'
);

comment on type public.franchise_resource_member_status is
  'Per-member engagement state for a franchise resource.';

-- ---------------------------------------------------------------------------
-- Taxonomy helper (category / course / period identities)
-- ---------------------------------------------------------------------------
create table public.franchise_resource_taxonomies (
  id bigint generated by default as identity primary key,
  place public.franchise_resource_taxonomy_place not null,
  kind public.franchise_resource_taxonomy_kind not null,
  alias text not null,
  label text not null,
  icon text,
  image_url text,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint franchise_resource_taxonomies_alias_format check (
    alias ~ '^[a-z0-9]+(?:[-_][a-z0-9]+)*$'
  ),
  constraint franchise_resource_taxonomies_label_length check (
    char_length(trim(label)) between 1 and 256
  ),
  constraint franchise_resource_taxonomies_sort_order_non_negative check (
    sort_order >= 0
  ),
  constraint franchise_resource_taxonomies_kind_alias_unique unique (kind, alias)
);

comment on table public.franchise_resource_taxonomies is
  'Lookup identities for franchise resource category, course, and period fields.';
comment on column public.franchise_resource_taxonomies.kind is
  'Which dimension this row describes: category, course, or period.';
comment on column public.franchise_resource_taxonomies.alias is
  'Stable machine key within a kind (lowercase kebab/snake).';
comment on column public.franchise_resource_taxonomies.label is
  'Human-readable label shown in filters and resource metadata.';

create index franchise_resource_taxonomies_kind_active_sort_idx
  on public.franchise_resource_taxonomies (kind, is_active, sort_order, label);

create trigger franchise_resource_taxonomies_set_updated_at
  before update on public.franchise_resource_taxonomies
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Global franchise resources
-- ---------------------------------------------------------------------------
create table public.franchise_resources (
  id bigint generated by default as identity primary key,
  type public.franchise_resource_type not null,
  title text not null,
  slug text not null,
  category_id bigint references public.franchise_resource_taxonomies (id) on delete set null,
  course_id bigint references public.franchise_resource_taxonomies (id) on delete set null,
  period_id bigint references public.franchise_resource_taxonomies (id) on delete set null,
  author_id uuid references auth.users (id) on delete set null,
  author_name text,
  icon text,
  description text,
  summary text,
  content text,
  content_format text not null default 'html',
  attached_files jsonb not null default '[]'::jsonb,
  content_file text,
  video_file text,
  course_duration interval,
  version text,
  is_published boolean not null default false,
  is_featured boolean not null default false,
  is_mandatory boolean not null default false,
  requires_acknowledgement boolean not null default false,
  sort_order integer not null default 0,
  tags text[] not null default '{}'::text[],
  external_url text,
  thumbnail_url text,
  estimated_read_minutes integer,
  effective_from timestamptz,
  effective_until timestamptz,
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  reference jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint franchise_resources_slug_format check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  constraint franchise_resources_slug_unique unique (slug),
  constraint franchise_resources_title_length check (
    char_length(trim(title)) between 1 and 512
  ),
  constraint franchise_resources_content_format_allowed check (
    content_format in ('html', 'markdown', 'plain')
  ),
  constraint franchise_resources_attached_files_is_array check (
    jsonb_typeof(attached_files) = 'array'
  ),
  constraint franchise_resources_sort_order_non_negative check (
    sort_order >= 0
  ),
  constraint franchise_resources_estimated_read_minutes_non_negative check (
    estimated_read_minutes is null or estimated_read_minutes >= 0
  ),
  constraint franchise_resources_effective_range check (
    effective_from is null
    or effective_until is null
    or effective_from <= effective_until
  )
);

comment on table public.franchise_resources is
  'Global franchise portal resources (announcements, documents, menu training) visible to franchise members.';
comment on column public.franchise_resources.type is
  'Resource kind: announcement, document, or menu_training.';
comment on column public.franchise_resources.category_id is
  'Optional taxonomy reference (e.g. category for documents, folder for announcements).';
comment on column public.franchise_resources.course_id is
  'Optional taxonomy reference; must point to a taxonomy row with kind = course.';
comment on column public.franchise_resources.period_id is
  'Optional taxonomy reference; must point to a taxonomy row with kind = period.';
comment on column public.franchise_resources.author_id is
  'Optional internal author (auth user).';
comment on column public.franchise_resources.author_name is
  'Display author when author_id is null (e.g. HQ team name).';
comment on column public.franchise_resources.description is
  'Longer description or body intro shown in listings and detail views.';
comment on column public.franchise_resources.summary is
  'Short preview line for inbox/list rows.';
comment on column public.franchise_resources.content is
  'Primary rich text body (HTML or markdown depending on content_format).';
comment on column public.franchise_resources.attached_files is
  'JSON array of attachment objects, e.g. [{ "name", "url", "mime_type", "size_bytes" }].';
comment on column public.franchise_resources.content_file is
  'Primary downloadable document URL (PDF, manual, SOP, etc.).';
comment on column public.franchise_resources.video_file is
  'Optional training video URL.';
comment on column public.franchise_resources.course_duration is
  'Estimated duration for menu_training resources.';
comment on column public.franchise_resources.is_mandatory is
  'When true, franchise members should complete or acknowledge this resource.';
comment on column public.franchise_resources.requires_acknowledgement is
  'When true, member must explicitly acknowledge after reading.';
comment on column public.franchise_resources.effective_from is
  'Optional start of visibility window for time-bound announcements/policies.';
comment on column public.franchise_resources.effective_until is
  'Optional end of visibility window.';
comment on column public.franchise_resources.metadata is
  'Extensible admin metadata (audit notes, custom fields).';
comment on column public.franchise_resources.reference is
  'Admin asset tracking JSON, e.g. {"uploaded":[{"path","publicUrl","fileName","uploadedAt"}]}.';

create index franchise_resources_type_published_idx
  on public.franchise_resources (type, is_published, sort_order, published_at desc);

create index franchise_resources_category_published_idx
  on public.franchise_resources (category_id, is_published, sort_order);

create index franchise_resources_course_published_idx
  on public.franchise_resources (course_id, is_published, sort_order);

create index franchise_resources_period_published_idx
  on public.franchise_resources (period_id, is_published, sort_order);

create index franchise_resources_featured_published_idx
  on public.franchise_resources (is_featured, is_published, published_at desc)
  where is_featured = true;

create index franchise_resources_tags_gin_idx
  on public.franchise_resources using gin (tags);

create trigger franchise_resources_set_updated_at
  before update on public.franchise_resources
  for each row
  execute function public.set_updated_at();

-- Ensure course_id and period_id taxonomy FK targets match the expected kind.
create or replace function public.enforce_franchise_resource_taxonomy_refs()
returns trigger
language plpgsql
as $$
declare
  v_kind public.franchise_resource_taxonomy_kind;
begin
  if new.course_id is not null then
    select kind into strict v_kind
    from public.franchise_resource_taxonomies
    where id = new.course_id;

    if v_kind <> 'course'::public.franchise_resource_taxonomy_kind then
      raise exception 'course_id must reference a taxonomy row with kind = course'
        using errcode = '23514';
    end if;
  end if;

  if new.period_id is not null then
    select kind into strict v_kind
    from public.franchise_resource_taxonomies
    where id = new.period_id;

    if v_kind <> 'period'::public.franchise_resource_taxonomy_kind then
      raise exception 'period_id must reference a taxonomy row with kind = period'
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

comment on function public.enforce_franchise_resource_taxonomy_refs() is
  'Validates course_id and period_id reference taxonomies of the matching kind.';

create trigger franchise_resources_enforce_taxonomy_refs
  before insert or update of course_id, period_id
  on public.franchise_resources
  for each row
  execute function public.enforce_franchise_resource_taxonomy_refs();

-- ---------------------------------------------------------------------------
-- Per-member resource state (1 row per member per resource)
-- ---------------------------------------------------------------------------
create table public.franchise_resource_member_states (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.franchise_resources (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  status public.franchise_resource_member_status not null default 'not_seen',
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  completed_at timestamptz,
  progress_percent smallint not null default 0,
  acknowledged_at timestamptz,
  is_favourite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint franchise_resource_member_states_resource_user_unique
    unique (resource_id, user_id),
  constraint franchise_resource_member_states_progress_range check (
    progress_percent between 0 and 100
  ),
  constraint franchise_resource_member_states_seen_timestamps check (
    status = 'not_seen'::public.franchise_resource_member_status
    or first_seen_at is not null
  ),
  constraint franchise_resource_member_states_completed_timestamp check (
    status <> 'completed'::public.franchise_resource_member_status
    or completed_at is not null
  )
);

comment on table public.franchise_resource_member_states is
  'Tracks each franchise member''s seen/completed status for a franchise resource.';
comment on column public.franchise_resource_member_states.first_seen_at is
  'When the member first opened the resource.';
comment on column public.franchise_resource_member_states.last_seen_at is
  'Most recent time the member opened the resource.';
comment on column public.franchise_resource_member_states.completed_at is
  'When the member marked the resource completed (or training finished).';
comment on column public.franchise_resource_member_states.progress_percent is
  'Optional progress for menu_training (0–100).';
comment on column public.franchise_resource_member_states.acknowledged_at is
  'When the member explicitly acknowledged a requires_acknowledgement resource.';

create index franchise_resource_member_states_user_status_idx
  on public.franchise_resource_member_states (user_id, status, updated_at desc);

create index franchise_resource_member_states_resource_status_idx
  on public.franchise_resource_member_states (resource_id, status);

create trigger franchise_resource_member_states_set_updated_at
  before update on public.franchise_resource_member_states
  for each row
  execute function public.set_updated_at();

create or replace function public.sync_franchise_resource_member_state_timestamps()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'seen'::public.franchise_resource_member_status then
    if new.first_seen_at is null then
      new.first_seen_at := coalesce(new.last_seen_at, now());
    end if;
    new.last_seen_at := coalesce(new.last_seen_at, now());
    new.completed_at := null;
    new.progress_percent := greatest(coalesce(new.progress_percent, 0), 1);
  elsif new.status = 'completed'::public.franchise_resource_member_status then
    new.first_seen_at := coalesce(new.first_seen_at, now());
    new.last_seen_at := coalesce(new.last_seen_at, now());
    new.completed_at := coalesce(new.completed_at, now());
    new.progress_percent := 100;
  else
    new.first_seen_at := null;
    new.last_seen_at := null;
    new.completed_at := null;
    new.acknowledged_at := null;
    new.progress_percent := 0;
  end if;

  return new;
end;
$$;

comment on function public.sync_franchise_resource_member_state_timestamps() is
  'Keeps first_seen_at, last_seen_at, completed_at, and progress aligned with status.';

create trigger franchise_resource_member_states_sync_timestamps
  before insert or update of status, first_seen_at, last_seen_at, completed_at, progress_percent
  on public.franchise_resource_member_states
  for each row
  execute function public.sync_franchise_resource_member_state_timestamps();

-- ---------------------------------------------------------------------------
-- Access helpers
-- ---------------------------------------------------------------------------
create or replace function public.can_access_franchise_resources()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select public.is_admin()
    or public.user_has_privilege('franchise'::public.business_type);
$$;

comment on function public.can_access_franchise_resources() is
  'True for admins and users with the franchise portal privilege.';

create or replace function public.franchise_resource_is_visible(
  resource public.franchise_resources
)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select resource.is_published
    and (resource.effective_from is null or resource.effective_from <= now())
    and (resource.effective_until is null or resource.effective_until > now());
$$;

comment on function public.franchise_resource_is_visible(public.franchise_resources) is
  'True when a franchise resource is currently published and within its effective window.';

grant execute on function public.can_access_franchise_resources()
  to authenticated, service_role;
grant execute on function public.franchise_resource_is_visible(public.franchise_resources)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.franchise_resource_taxonomies enable row level security;
alter table public.franchise_resources enable row level security;
alter table public.franchise_resource_member_states enable row level security;

-- Taxonomies: franchise members read active rows; admins manage all.
create policy "Franchise members can read active taxonomies"
  on public.franchise_resource_taxonomies
  for select
  to authenticated
  using (
    public.can_access_franchise_resources()
    and is_active = true
  );

create policy "Admins can read all franchise resource taxonomies"
  on public.franchise_resource_taxonomies
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert franchise resource taxonomies"
  on public.franchise_resource_taxonomies
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update franchise resource taxonomies"
  on public.franchise_resource_taxonomies
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete franchise resource taxonomies"
  on public.franchise_resource_taxonomies
  for delete
  to authenticated
  using (public.is_admin());

-- Resources: franchise members read published/visible rows; admins manage all.
create policy "Franchise members can read visible franchise resources"
  on public.franchise_resources
  for select
  to authenticated
  using (
    public.can_access_franchise_resources()
    and public.franchise_resource_is_visible(franchise_resources)
  );

create policy "Admins can read all franchise resources"
  on public.franchise_resources
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert franchise resources"
  on public.franchise_resources
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update franchise resources"
  on public.franchise_resources
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete franchise resources"
  on public.franchise_resources
  for delete
  to authenticated
  using (public.is_admin());

-- Member states: users manage their own rows; admins manage all.
create policy "Franchise members can read own resource states"
  on public.franchise_resource_member_states
  for select
  to authenticated
  using (
    public.can_access_franchise_resources()
    and user_id = auth.uid()
  );

create policy "Admins can read all franchise resource member states"
  on public.franchise_resource_member_states
  for select
  to authenticated
  using (public.is_admin());

create policy "Franchise members can insert own resource states"
  on public.franchise_resource_member_states
  for insert
  to authenticated
  with check (
    public.can_access_franchise_resources()
    and user_id = auth.uid()
    and exists (
      select 1
      from public.franchise_resources as resource
      where resource.id = resource_id
        and public.franchise_resource_is_visible(resource)
    )
  );

create policy "Franchise members can update own resource states"
  on public.franchise_resource_member_states
  for update
  to authenticated
  using (
    public.can_access_franchise_resources()
    and user_id = auth.uid()
  )
  with check (
    public.can_access_franchise_resources()
    and user_id = auth.uid()
  );

create policy "Admins can insert franchise resource member states"
  on public.franchise_resource_member_states
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update franchise resource member states"
  on public.franchise_resource_member_states
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete franchise resource member states"
  on public.franchise_resource_member_states
  for delete
  to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
grant select on public.franchise_resource_taxonomies to authenticated;
grant insert, update, delete on public.franchise_resource_taxonomies to authenticated;
grant all on public.franchise_resource_taxonomies to service_role;

grant select on public.franchise_resources to authenticated;
grant insert, update, delete on public.franchise_resources to authenticated;
grant all on public.franchise_resources to service_role;

grant select, insert, update on public.franchise_resource_member_states to authenticated;
grant all on public.franchise_resource_member_states to service_role;

grant usage on type public.franchise_resource_type to authenticated, service_role;
grant usage on type public.franchise_resource_taxonomy_kind to authenticated, service_role;
grant usage on type public.franchise_resource_member_status to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Seed document categories and catalogue rows
-- Files referenced in content_file / attached_files use storage paths under
-- franchise-documents/; upload the matching assets to those paths before publishing.
-- ---------------------------------------------------------------------------
insert into public.franchise_resource_taxonomies (
  place,
  kind,
  alias,
  label,
  sort_order,
  is_active
)
values
  ('document', 'category', 'legal-documents', 'Legal Documents', 1, true),
  ('document', 'category', 'brand-documents', 'Brand Documents', 2, true),
  ('document', 'category', 'operations-manuals', 'Operations Manuals', 3, true),
  ('document', 'category', 'recipe-portion-control', 'Recipe & Portion Control', 4, true),
  ('document', 'category', 'training-documents', 'Training Documents', 5, true),
  ('document', 'category', 'report-documents', 'Report Documents', 6, true),
  ('document', 'category', 'marketing', 'Marketing', 7, true),
  ('document', 'category', 'supplier-central-kitchen', 'Supplier & Central Kitchen', 8, true),
  ('document', 'category', 'hr-staff', 'HR & Staff', 9, true),
  ('document', 'category', 'compliance', 'Compliance', 10, true)
on conflict (kind, alias) do update
set
  place = excluded.place,
  label = excluded.label,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

with seed_documents (
  category_alias,
  sort_order,
  title,
  slug,
  content_file,
  attached_files
) as (
  values
    -- 1. Legal Documents
    ('legal-documents', 1, 'Franchise Agreement', 'franchise-agreement', null::text, '[]'::jsonb),
    ('legal-documents', 2, 'Disclosure Document', 'disclosure-document', null, '[]'::jsonb),
    ('legal-documents', 3, 'Information Statement', 'information-statement', null, '[]'::jsonb),
    ('legal-documents', 4, 'Franchise Register Information', 'franchise-register-information', null, '[]'::jsonb),
    ('legal-documents', 5, 'Privacy Policy', 'privacy-policy', null, '[]'::jsonb),
    ('legal-documents', 6, 'Confidentiality Agreement', 'confidentiality-agreement', null, '[]'::jsonb),
    ('legal-documents', 7, 'Trademark Licence', 'trademark-licence', null, '[]'::jsonb),

    -- 2. Brand Documents
    ('brand-documents', 1, 'Brand Manual', 'brand-manual', null, '[]'::jsonb),
    ('brand-documents', 2, 'Logo Files', 'logo-files', null, '[]'::jsonb),
    ('brand-documents', 3, 'Colour Palette', 'colour-palette', null, '[]'::jsonb),
    ('brand-documents', 4, 'Font Guide', 'font-guide', null, '[]'::jsonb),
    ('brand-documents', 5, 'Packaging Guide', 'packaging-guide', null, '[]'::jsonb),
    ('brand-documents', 6, 'Signage Guide', 'signage-guide', null, '[]'::jsonb),

    -- 3. Operations Manuals
    ('operations-manuals', 1, 'Kitchen Operations Manual', 'kitchen-operations-manual', null, '[]'::jsonb),
    ('operations-manuals', 2, 'FOH Manual', 'foh-manual', null, '[]'::jsonb),
    ('operations-manuals', 3, 'Store Opening Manual', 'store-opening-manual', null, '[]'::jsonb),
    ('operations-manuals', 4, 'Store Closing Manual', 'store-closing-manual', null, '[]'::jsonb),
    ('operations-manuals', 5, 'Food Safety Manual', 'food-safety-manual', null, '[]'::jsonb),
    ('operations-manuals', 6, 'Cleaning Manual', 'cleaning-manual', null, '[]'::jsonb),
    (
      'operations-manuals',
      7,
      'Uber Eats & DoorDash Manual',
      'uber-eats-doordash-manual',
      null,
      jsonb_build_array(
        jsonb_build_object(
          'name', 'DoorDash Tablet How-To Guide',
          'url', 'franchise-documents/DoorDash_Tablet_How-To_Guide-August-22.pdf',
          'mime_type', 'application/pdf'
        ),
        jsonb_build_object(
          'name', 'Uber Eats Orders Training Guide',
          'url', 'franchise-documents/Uber_Eats_Orders_Training_Guide_USC_2021.pdf',
          'mime_type', 'application/pdf'
        )
      )
    ),

    -- 4. Recipe & Portion Control
    (
      'recipe-portion-control',
      1,
      'Recipe Cards',
      'recipe-cards',
      'franchise-documents/Saigon Express Preparation Recipe 2026 v1.pdf',
      '[]'::jsonb
    ),
    ('recipe-portion-control', 2, 'Portion Charts', 'portion-charts', null, '[]'::jsonb),
    ('recipe-portion-control', 3, 'Sauce Recipes', 'sauce-recipes', null, '[]'::jsonb),
    ('recipe-portion-control', 4, 'Prep Sheets', 'prep-sheets', null, '[]'::jsonb),
    ('recipe-portion-control', 5, 'Catering Portion Guide', 'catering-portion-guide', null, '[]'::jsonb),
    ('recipe-portion-control', 6, 'Costing Sheets', 'costing-sheets', null, '[]'::jsonb),

    -- 5. Training Documents
    (
      'training-documents',
      1,
      'Franchisee Training Program',
      'franchisee-training-program',
      'franchise-documents/FOH Training Program.docx',
      '[]'::jsonb
    ),
    (
      'training-documents',
      2,
      'Staff Training Checklist',
      'staff-training-checklist',
      'franchise-documents/BOH Training Program.docx',
      '[]'::jsonb
    ),
    ('training-documents', 3, 'Manager Training Checklist', 'manager-training-checklist', null, '[]'::jsonb),
    ('training-documents', 4, 'Quiz & Assessment', 'quiz-assessment', null, '[]'::jsonb),
    (
      'training-documents',
      5,
      'Delivery Platform Staff Training Manual',
      'delivery-platform-staff-training-manual',
      'franchise-documents/Saigon_Express Delivery Platform Staff Training Manual 2026.pdf',
      '[]'::jsonb
    ),
    ('training-documents', 6, 'Sign-off Forms', 'sign-off-forms', null, '[]'::jsonb),

    -- 6. Report Documents
    (
      'report-documents',
      1,
      'Daily Sales Report',
      'daily-sales-report',
      'franchise-documents/Saigon Express_Daily Sales Report.xlsx',
      '[]'::jsonb
    ),
    ('report-documents', 2, 'Weekly KPI Report', 'weekly-kpi-report', null, '[]'::jsonb),
    ('report-documents', 3, 'Royalty Report', 'royalty-report', null, '[]'::jsonb),
    ('report-documents', 4, 'Marketing Levy Report', 'marketing-levy-report', null, '[]'::jsonb),
    (
      'report-documents',
      5,
      'Stocktake Template',
      'stocktake-template',
      'franchise-documents/Saigon Express_Stocktake Template.xlsx',
      '[]'::jsonb
    ),
    ('report-documents', 6, 'Labour Cost Tracker', 'labour-cost-tracker', null, '[]'::jsonb),

    -- 7. Marketing
    (
      'marketing',
      1,
      'Grand Opening Plan',
      'grand-opening-plan',
      'franchise-documents/Saigon Express_Grand Opening Marketing Plan.docx',
      '[]'::jsonb
    ),
    (
      'marketing',
      2,
      'Monthly Marketing Calendar',
      'monthly-marketing-calendar',
      'franchise-documents/Saigon Express_Marketing Calendar.xlsx',
      '[]'::jsonb
    ),
    ('marketing', 3, 'Social Media Templates', 'social-media-templates', null, '[]'::jsonb),
    ('marketing', 4, 'Poster Templates', 'poster-templates', null, '[]'::jsonb),
    ('marketing', 5, 'Review Response Templates', 'review-response-templates', null, '[]'::jsonb),
    (
      'marketing',
      6,
      'Local Area Marketing Guide',
      'local-area-marketing-guide',
      'franchise-documents/Saigon Express_LAM Guide Tasmania.docx',
      '[]'::jsonb
    ),

    -- 8. Supplier & Central Kitchen
    ('supplier-central-kitchen', 1, 'Approved Supplier List', 'approved-supplier-list', null, '[]'::jsonb),
    (
      'supplier-central-kitchen',
      2,
      'Central Kitchen Order Form',
      'central-kitchen-order-form',
      'franchise-documents/Saigon Express_Central Kitchen Order Form.xlsx',
      '[]'::jsonb
    ),
    ('supplier-central-kitchen', 3, 'Delivery Schedule', 'delivery-schedule', null, '[]'::jsonb),
    (
      'supplier-central-kitchen',
      4,
      'Product Specification Sheets',
      'product-specification-sheets',
      'franchise-documents/Saigon Express_Product Spec Sheets.xlsx',
      '[]'::jsonb
    ),
    (
      'supplier-central-kitchen',
      5,
      'Quality Complaint Form',
      'quality-complaint-form',
      'franchise-documents/Saigon Express_Quality Complaint Form.docx',
      '[]'::jsonb
    ),

    -- 9. HR & Staff
    (
      'hr-staff',
      1,
      'Position Descriptions',
      'position-descriptions',
      'franchise-documents/Saigon Express_Job Descriptions.docx',
      '[]'::jsonb
    ),
    (
      'hr-staff',
      2,
      'Staff Handbook',
      'staff-handbook',
      'franchise-documents/Saigon Express_Staff Handbook.docx',
      '[]'::jsonb
    ),
    ('hr-staff', 3, 'Uniform Policy', 'uniform-policy', null, '[]'::jsonb),
    (
      'hr-staff',
      4,
      'Leave Request Form',
      'leave-request-form',
      'franchise-documents/Saigon Express_Leave Request Form.docx',
      '[]'::jsonb
    ),
    (
      'hr-staff',
      5,
      'Incident Report Form',
      'incident-report-form',
      'franchise-documents/Saigon Express_Incident Report.docx',
      '[]'::jsonb
    ),
    (
      'hr-staff',
      6,
      'Warning Letter Template',
      'warning-letter-template',
      'franchise-documents/Saigon Express_Warning Letters.docx',
      '[]'::jsonb
    ),

    -- 10. Compliance
    (
      'compliance',
      1,
      'Food Safety Logs + Temperature Logs + WHS Checklist',
      'food-safety-logs-temperature-logs-whs-checklist',
      'franchise-documents/Saigon Express_Food Safety Logs.xlsx',
      '[]'::jsonb
    ),
    (
      'compliance',
      2,
      'Cleaning Logs + Pest Control Records',
      'cleaning-logs-pest-control-records',
      'franchise-documents/Saigon Express_Cleaning and Pest Logs.xlsx',
      '[]'::jsonb
    ),
    (
      'compliance',
      3,
      'Liquor Licence Rules',
      'liquor-licence-rules',
      'franchise-documents/Saigon_Express_Liquor Licence Guide.docx',
      '[]'::jsonb
    ),
    ('compliance', 4, 'Insurance Documents', 'insurance-documents', null, '[]'::jsonb)
)
insert into public.franchise_resources (
  type,
  title,
  slug,
  category_id,
  author_name,
  content_file,
  attached_files,
  sort_order,
  is_published,
  published_at,
  metadata
)
select
  'document'::public.franchise_resource_type,
  seed.title,
  seed.slug,
  taxonomy.id,
  'Franchise HQ',
  seed.content_file,
  seed.attached_files,
  seed.sort_order,
  true,
  now(),
  jsonb_build_object(
    'seed',
    jsonb_build_object(
      'source', '20260624120000_franchise_resources',
      'category_alias', seed.category_alias
    )
  )
from seed_documents seed
join public.franchise_resource_taxonomies taxonomy
  on taxonomy.kind = 'category'
 and taxonomy.alias = seed.category_alias
on conflict (slug) do update
set
  type = excluded.type,
  title = excluded.title,
  category_id = excluded.category_id,
  author_name = excluded.author_name,
  content_file = excluded.content_file,
  attached_files = excluded.attached_files,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  published_at = coalesce(public.franchise_resources.published_at, excluded.published_at),
  metadata = public.franchise_resources.metadata || excluded.metadata;
