-- Menu categories used by the public menu UI.

create table public.categories (
  id bigint generated by default as identity primary key,
  alias text not null unique,
  name text not null,
  description text,
  "imageUrl" text,
  addon text[] not null default '{}'::text[]
);

comment on table public.categories is
  'Menu categories used by the public site, including category image and add-on pairing rules.';

create index categories_alias_idx
  on public.categories (alias);

alter table public.categories enable row level security;

create policy "Anyone can read categories"
  on public.categories
  for select
  to anon, authenticated
  using (true);

grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant all on public.categories to service_role;

-- Admin CRUD
create policy "Admins can read all categories"
  on public.categories
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert categories"
  on public.categories
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update categories"
  on public.categories
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete categories"
  on public.categories
  for delete
  to authenticated
  using (public.is_admin());

insert into public.categories (
  alias,
  name,
  description,
  "imageUrl",
  addon
)
values
  (
    'Entrée',
    'Entrée',
    null,
    '/manus-storage/entree-seafood-spring-rolls_f060f6bd.jpg',
    '{}'::text[]
  ),
  (
    'Bánh Mì',
    'Bánh Mì',
    null,
    '/manus-storage/crispyroastporkbanhmi_ce355122.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Rice Paper Rolls',
    'Rice Paper Rolls',
    null,
    '/manus-storage/saigo_express__Cuon_Vietnamese_prawn_rice_paper_rolls_NativeLarge_5da191dd.png',
    '{}'::text[]
  ),
  (
    'Pho',
    'Pho',
    null,
    '/manus-storage/pho-1_92a9985e.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Noodle Soup',
    'Noodle Soup',
    null,
    '/manus-storage/pho-2_4fc44f9f.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Bun Bowl',
    'Bun Bowl',
    null,
    '/manus-storage/bun-bowl-1_3b12ea6c.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Rice Dishes',
    'Rice Dishes',
    null,
    '/manus-storage/banh-mi-2_7d02846f.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Grill Signatures',
    'Grill Signatures',
    null,
    '/manus-storage/banh-mi-1_9ba4dcf0.jpg',
    array['Drinks', 'Rice Paper Rolls']::text[]
  ),
  (
    'Bao Buns',
    'Bao Buns',
    null,
    '/manus-storage/banh-mi-3_465cb7d1.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Omelette',
    'Omelette',
    null,
    '/manus-storage/bun-bowl-1_3b12ea6c.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Burgers & Chicken',
    'Burgers & Chicken',
    null,
    '/manus-storage/banh-mi-2_7d02846f.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Meal Deals',
    'Meal Deals',
    null,
    '/manus-storage/banh-mi-3_465cb7d1.jpg',
    array['Drinks', 'Entrée']::text[]
  ),
  (
    'Drinks',
    'Drinks',
    null,
    '/manus-storage/spring-rolls-2_f1e40ae6.jpg',
    '{}'::text[]
  )
on conflict (alias) do update set
  name = excluded.name,
  description = excluded.description,
  "imageUrl" = excluded."imageUrl",
  addon = excluded.addon;
