-- Featured customer reviews (public site carousel).

create table public.featured_reviews (
  id bigint primary key,
  reviewer_name text not null,
  rating smallint not null,
  review_text text not null,
  location text,
  is_featured boolean not null default true,
  created_at timestamptz not null default now(),
  constraint featured_reviews_rating_range check (rating >= 1 and rating <= 5)
);

comment on table public.featured_reviews is
  'Customer reviews shown on the public site (e.g. home page carousel).';

create index featured_reviews_is_featured_created_at_idx
  on public.featured_reviews (is_featured, created_at desc);

alter table public.featured_reviews enable row level security;

create policy "Anyone can read featured reviews"
  on public.featured_reviews
  for select
  to anon, authenticated
  using (is_featured = true);

grant select on public.featured_reviews to anon, authenticated;
grant insert, update, delete on public.featured_reviews to authenticated;
grant all on public.featured_reviews to service_role;

-- Admin CRUD
create policy "Admins can read all featured reviews"
  on public.featured_reviews
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert featured reviews"
  on public.featured_reviews
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update featured reviews"
  on public.featured_reviews
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete featured reviews"
  on public.featured_reviews
  for delete
  to authenticated
  using (public.is_admin());

-- Seed from refs/samples/reviews.json (batch featuredReviews). Regenerate:
--   npm run generate:featured-reviews-seed
-- BEGIN featured_reviews seed (generated by scripts/generate-featured-reviews-seed.mjs)
insert into public.featured_reviews (
  id,
  reviewer_name,
  rating,
  review_text,
  location,
  is_featured,
  created_at
)
values
  (
    4,
    'David K.',
    5,
    'Great value for money. The mixed entrée platter is perfect for sharing and the spring rolls are crispy and delicious. Service is quick even during the lunch rush. Will definitely be back!',
    'Glenorchy, TAS',
    true,
    '2026-04-29T04:28:53.000Z'::timestamptz
  ),
  (
    5,
    'Emma R.',
    5,
    'I ordered the bún bowl and it was absolutely delicious — light, fresh, and full of flavour. Love that there are healthy options on the menu. The staff were super helpful with my dietary questions too.',
    'Kingston, TAS',
    true,
    '2026-04-29T04:28:53.000Z'::timestamptz
  ),
  (
    6,
    'Michael C.',
    4,
    'Really solid Vietnamese food at a great price. The crackling roasted pork is a must-try — crispy skin, tender meat, and the dipping sauce is amazing. Only reason I am not giving 5 stars is the wait time on busy days.',
    'Moonah, TAS',
    true,
    '2026-04-29T04:28:53.000Z'::timestamptz
  ),
  (
    1,
    'Sarah M.',
    5,
    'Absolutely love Saigon Express! The bánh mì is the best I have had outside of Vietnam. Fresh ingredients, generous portions, and the staff are always so friendly. My go-to lunch spot in Hobart.',
    'Hobart, TAS',
    true,
    '2026-04-29T04:28:52.000Z'::timestamptz
  ),
  (
    2,
    'James T.',
    5,
    'The pho here is incredible — rich, deeply flavoured broth that warms you right through on a cold Tassie day. I have tried a lot of Vietnamese restaurants and this is genuinely top tier. Highly recommend the combination beef pho.',
    'Sandy Bay, TAS',
    true,
    '2026-04-29T04:28:52.000Z'::timestamptz
  ),
  (
    3,
    'Linh N.',
    5,
    'As a Vietnamese person, I can say this is the real deal. The flavours are authentic and the food reminds me of home. The lemongrass chicken rice is my favourite — perfectly balanced and always fresh.',
    'Launceston, TAS',
    true,
    '2026-04-29T04:28:52.000Z'::timestamptz
  )
on conflict (id) do update set
  reviewer_name = excluded.reviewer_name,
  rating = excluded.rating,
  review_text = excluded.review_text,
  location = excluded.location,
  is_featured = excluded.is_featured,
  created_at = excluded.created_at;
-- END featured_reviews seed
