-- Careers job listings (moved from messages/en.json Careers.jobs).

create table public.job_listings (
  id bigint generated by default as identity primary key,
  title text not null,
  department text not null,
  employment_type text not null,
  location text not null,
  salary text not null,
  badge text,
  badge_color text not null default '',
  summary text not null,
  responsibilities text[] not null default '{}'::text[],
  requirements text[] not null default '{}'::text[],
  perks text[] not null default '{}'::text[],
  is_active boolean not null default true,
  sort_order integer not null default 0,
  store_id bigint references public.store_locations (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint job_listings_title_length check (
    char_length(trim(title)) between 1 and 256
  ),
  constraint job_listings_department_length check (
    char_length(trim(department)) between 1 and 128
  ),
  constraint job_listings_employment_type_length check (
    char_length(trim(employment_type)) between 1 and 64
  ),
  constraint job_listings_location_length check (
    char_length(trim(location)) between 1 and 256
  ),
  constraint job_listings_salary_length check (
    char_length(trim(salary)) between 1 and 128
  ),
  constraint job_listings_badge_length check (
    badge is null or char_length(trim(badge)) between 1 and 64
  ),
  constraint job_listings_badge_color_length check (
    char_length(trim(badge_color)) <= 64
  ),
  constraint job_listings_summary_length check (
    char_length(trim(summary)) between 1 and 4000
  )
);

comment on table public.job_listings is
  'Published careers page job postings shown on /careers.';
comment on column public.job_listings.employment_type is
  'Employment arrangement label (e.g. Full-Time, Part-Time / Casual).';
comment on column public.job_listings.badge_color is
  'Tailwind background utility class for optional listing badge.';
comment on column public.job_listings.responsibilities is
  'Bullet list of key responsibilities.';
comment on column public.job_listings.requirements is
  'Bullet list of candidate requirements.';
comment on column public.job_listings.perks is
  'Bullet list of perks and benefits.';
comment on column public.job_listings.sort_order is
  'Display order on the careers page (lower first).';

create index job_listings_active_sort_idx
  on public.job_listings (is_active, sort_order, id);

create index job_listings_department_idx
  on public.job_listings (department);

create trigger job_listings_set_updated_at
  before update on public.job_listings
  for each row
  execute function public.set_updated_at();

alter table public.job_listings enable row level security;

grant select on public.job_listings to anon, authenticated;
grant insert, update, delete on public.job_listings to authenticated;
grant all on public.job_listings to service_role;

create policy "Anyone can read active job listings"
  on public.job_listings
  for select
  to anon, authenticated
  using (is_active = true);

create policy "Admins can read all job listings"
  on public.job_listings
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert job listings"
  on public.job_listings
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update job listings"
  on public.job_listings
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete job listings"
  on public.job_listings
  for delete
  to authenticated
  using (public.is_admin());

insert into public.job_listings (
  id,
  title,
  department,
  employment_type,
  location,
  salary,
  badge,
  badge_color,
  summary,
  responsibilities,
  requirements,
  perks,
  is_active,
  sort_order
)
overriding system value
values
  (1, 'Head Wok Chef', 'Kitchen', 'Full-Time', 'North Hobart / CBD', '$65,000 – $80,000 + super', 'SENIOR ROLE', 'bg-red-600', 'Lead our kitchen brigade across our busiest locations. You will own the wok station, set the quality standard for every dish that leaves the pass, and mentor junior kitchen staff in authentic Vietnamese cooking techniques.', ARRAY['Execute the full Saigon Express menu to specification, with a focus on wok-based dishes, pho, and bún bowls', 'Maintain consistent flavour profiles across all menu items during high-volume service periods', 'Train and supervise junior cooks and kitchen hands in Vietnamese cooking techniques', 'Manage mise en place, prep schedules, and kitchen workflow to minimise ticket times', 'Monitor food quality, portion control, and plate presentation standards', 'Assist the Restaurant Manager with ordering, stock rotation, and waste reduction', 'Uphold all food safety, hygiene, and HACCP standards at all times', 'Contribute ideas for seasonal specials and menu development']::text[], ARRAY['Minimum 3 years'' experience as a wok chef or senior cook in a Vietnamese or Asian restaurant', 'Proven ability to work at speed and maintain quality during peak service', 'Strong knowledge of Vietnamese flavour profiles, stocks, and sauces', 'Food Safety Supervisor certificate (or willingness to obtain)', 'Ability to work a rotating roster including weekends and public holidays', 'Team leadership experience is highly regarded']::text[], ARRAY['30% staff meal discount', 'Career progression to Head Chef', 'Training in our central kitchen', 'Uniform provided']::text[], true, 1),
  (2, 'Sous Chef', 'Kitchen', 'Full-Time', 'Any Tasmanian Location', '$58,000 – $68,000 + super', null, '', 'Support the Head Chef in running a smooth, high-quality kitchen operation. You will be responsible for daily prep, service execution, and stepping up as acting Head Chef when required.', ARRAY['Assist the Head Chef in all aspects of kitchen management and service', 'Lead the kitchen team during service in the Head Chef''s absence', 'Oversee daily prep lists, ensuring all stations are fully set up before service', 'Monitor food costs, portion sizes, and wastage in line with targets', 'Conduct daily temperature checks and food safety documentation', 'Train new kitchen staff and provide ongoing coaching', 'Maintain a clean, organised, and safe kitchen environment']::text[], ARRAY['2+ years'' experience as a Sous Chef or Senior Cook in a fast-paced kitchen', 'Solid understanding of Vietnamese or Asian cuisine', 'Food Safety Supervisor certificate', 'Strong organisational skills and ability to multitask under pressure', 'Flexible availability including weekends']::text[], ARRAY['30% staff meal discount', 'Clear pathway to Head Chef', 'Uniform provided', 'Paid training']::text[], true, 2),
  (3, 'Cook / Kitchen Hand', 'Kitchen', 'Full-Time / Part-Time', 'All Locations', '$24 – $30/hr + super', 'MULTIPLE POSITIONS', 'bg-amber-600', 'Join our kitchen team and learn the craft of authentic Vietnamese cooking. Whether you are an experienced cook or an enthusiastic beginner, we will train you to the Saigon Express standard.', ARRAY['Prepare ingredients and complete daily mise en place tasks', 'Assist with cooking during service under the direction of the Head Chef', 'Maintain cleanliness and organisation of your station throughout service', 'Complete end-of-shift cleaning duties to food safety standards', 'Receive and store deliveries, checking quality and rotating stock', 'Assist with dishwashing and general kitchen support as required']::text[], ARRAY['Passion for food and a willingness to learn', 'Ability to work efficiently in a fast-paced environment', 'Reliable, punctual, and a strong team player', 'Food handling certificate (or willingness to obtain — we will help)', 'Previous kitchen experience is an advantage but not essential']::text[], ARRAY['30% staff meal discount', 'Paid training', 'Flexible hours', 'Pathway to Cook or Sous Chef']::text[], true, 3),
  (4, 'Restaurant Manager', 'Management', 'Full-Time', 'North Hobart / CBD', '$70,000 – $85,000 + super + bonus', 'LEADERSHIP', 'bg-emerald-700', 'Take ownership of the daily operations of a Saigon Express location. You will lead a team of up to 15 staff, drive sales performance, and ensure every guest leaves with a smile.', ARRAY['Oversee all front-of-house and back-of-house operations for your location', 'Recruit, onboard, roster, and manage a team of up to 15 FOH and BOH staff', 'Drive revenue through upselling, promotions, and excellent guest experience', 'Monitor daily sales, labour costs, and COGS against budget targets', 'Manage stock ordering, supplier relationships, and inventory accuracy', 'Handle guest feedback and resolve complaints professionally and promptly', 'Ensure compliance with all food safety, liquor licensing, and OH&S regulations', 'Prepare weekly reports for the Operations Manager and Franchise Director', 'Champion the Saigon Express brand standards and culture at your location']::text[], ARRAY['3+ years'' experience managing a restaurant, café, or QSR location', 'Proven track record of leading and developing hospitality teams', 'Strong financial acumen — comfortable reading P&L reports', 'RSA certificate and Food Safety Supervisor certificate', 'Excellent communication and conflict-resolution skills', 'Flexible availability including weekends and public holidays']::text[], ARRAY['Performance bonus', '30% staff meal discount', 'Career path to Area Manager', 'Company phone', 'Paid leadership training']::text[], true, 4),
  (5, 'Assistant Restaurant Manager', 'Management', 'Full-Time', 'All Locations', '$58,000 – $68,000 + super', null, '', 'Support the Restaurant Manager in running a high-performing location. This is an ideal role for an experienced senior FOH team member ready to take the next step into management.', ARRAY['Assist the Restaurant Manager in all aspects of daily operations', 'Supervise FOH staff during service and act as duty manager when required', 'Open and close the venue, including cash reconciliation and end-of-day reporting', 'Handle guest feedback and escalations with professionalism', 'Assist with rostering, onboarding new staff, and conducting performance check-ins', 'Monitor stock levels and assist with ordering', 'Ensure brand standards and service procedures are followed consistently']::text[], ARRAY['2+ years'' experience in a senior FOH or team leader role', 'RSA certificate', 'Strong leadership presence and communication skills', 'Comfortable with POS systems and basic cash handling', 'Flexible availability including weekends']::text[], ARRAY['30% staff meal discount', 'Clear pathway to Restaurant Manager', 'Paid training', 'Uniform provided']::text[], true, 5),
  (6, 'Front of House (FOH) Team Leader', 'Front of House', 'Full-Time / Part-Time', 'All Locations', '$27 – $32/hr + super', null, '', 'Lead the floor during service, ensuring every guest receives a warm, efficient, and memorable Saigon Express experience. You will mentor junior FOH staff and be the first point of contact for guest feedback.', ARRAY['Lead the FOH team during service, directing staff to tables and stations', 'Greet and seat guests, manage waitlists, and oversee table turnover', 'Handle guest feedback and complaints promptly and professionally', 'Train and coach junior FOH staff in service standards and menu knowledge', 'Assist with opening and closing duties including cash reconciliation', 'Ensure the dining area is clean, well-presented, and fully stocked at all times', 'Communicate clearly with the kitchen team to manage ticket flow']::text[], ARRAY['2+ years'' experience in a FOH role, with at least 6 months in a team leader or senior capacity', 'RSA certificate', 'Excellent communication and interpersonal skills', 'Ability to stay calm and organised during busy service periods', 'Flexible availability including weekends and public holidays']::text[], ARRAY['30% staff meal discount', 'Pathway to Assistant Manager', 'Uniform provided', 'Flexible hours']::text[], true, 6),
  (7, 'Talented FOH Staff / Wait Staff', 'Front of House', 'Full-Time / Part-Time / Casual', 'All Locations', '$24 – $28/hr + super', 'NOW HIRING', 'bg-primary', 'Be the face of Saigon Express. We are always looking for warm, energetic, and guest-focused people to join our front-of-house team. No Vietnamese food experience required — just a genuine love of hospitality.', ARRAY['Welcome guests with warmth and enthusiasm, creating a memorable first impression', 'Take orders accurately using our POS system and communicate special requests to the kitchen', 'Deliver food and beverages promptly and check in on guest satisfaction', 'Maintain a thorough knowledge of the full Saigon Express menu, including ingredients and allergens', 'Keep the dining area clean, tidy, and well-presented throughout service', 'Process payments and handle cash and card transactions accurately', 'Assist with opening and closing side duties as directed', 'Upsell menu items, drinks, and catering packages where appropriate']::text[], ARRAY['Genuine passion for hospitality and creating great guest experiences', 'RSA certificate (or willingness to obtain — we will support you)', 'Reliable, punctual, and a strong team player', 'Ability to work at pace during busy service periods', 'Previous hospitality experience is an advantage but not essential', 'Flexible availability including weekends']::text[], ARRAY['30% staff meal discount', 'Flexible casual, part-time, or full-time hours', 'Uniform provided', 'Pathway to Team Leader and beyond']::text[], true, 7),
  (8, 'Barista / Drinks Specialist', 'Front of House', 'Part-Time / Casual', 'CBD / North Hobart', '$25 – $30/hr + super', null, '', 'Craft our Vietnamese iced coffee, homemade lemon tea, and full espresso menu for our guests. If you love coffee and Vietnamese drinks culture, this role is for you.', ARRAY['Prepare and serve espresso-based coffees, Vietnamese iced coffee, and homemade drinks to specification', 'Maintain the coffee machine, grinder, and drinks station to a high standard of cleanliness', 'Manage stock levels for coffee, milk, and drinks ingredients', 'Assist FOH staff during busy service periods', 'Engage with guests and share your knowledge of our drinks menu']::text[], ARRAY['Barista experience with a strong understanding of espresso technique', 'Interest in Vietnamese drinks culture is a bonus', 'RSA certificate', 'Friendly, guest-focused personality', 'Flexible availability including weekends']::text[], ARRAY['30% staff meal discount', 'Free coffee on shift', 'Flexible hours', 'Uniform provided']::text[], true, 8),
  (9, 'Delivery & Catering Coordinator', 'Operations', 'Full-Time / Part-Time', 'Hobart Region', '$26 – $32/hr + super', null, '', 'Coordinate our growing catering and delivery operations across Greater Hobart. You will be the logistics backbone of our catering business, ensuring every order arrives on time, at temperature, and presented perfectly.', ARRAY['Manage all catering order bookings, confirmations, and client communication', 'Coordinate delivery schedules and driver logistics for catering and wholesale orders', 'Pack and quality-check catering orders before dispatch', 'Liaise with the kitchen team to ensure catering orders are prepared on time', 'Maintain catering equipment, packaging inventory, and delivery vehicle cleanliness', 'Handle post-event follow-up with catering clients', 'Assist with the development of new catering packages and pricing']::text[], ARRAY['Experience in a logistics, events, or hospitality coordination role', 'Valid Australian driver''s licence', 'Strong organisational skills and attention to detail', 'Excellent communication skills — you will be the client''s main point of contact', 'Ability to lift and carry catering equipment (up to 15kg)', 'Food handling certificate']::text[], ARRAY['30% staff meal discount', 'Company vehicle for deliveries', 'Flexible hours', 'Pathway to Operations Manager']::text[], true, 9),
  (10, 'Wholesale & B2B Account Manager', 'Sales & Wholesale', 'Full-Time', 'Hobart (Travel Required)', '$60,000 – $72,000 + super + commission', null, '', 'Grow our wholesale business across Tasmania. You will manage relationships with existing café, grocery, and hospitality partners, and actively prospect for new B2B accounts.', ARRAY['Manage and grow a portfolio of wholesale accounts across Tasmania', 'Conduct regular client visits to ensure satisfaction and identify upsell opportunities', 'Prospect and onboard new B2B partners including cafés, delis, and corporate clients', 'Prepare and present wholesale proposals, pricing, and product samples', 'Coordinate with the warehouse team to ensure accurate and timely order fulfilment', 'Track sales performance and report weekly to the Operations Manager', 'Represent Saigon Express at trade events, food expos, and networking functions']::text[], ARRAY['2+ years'' experience in a B2B sales or account management role, preferably in food & beverage', 'Strong relationship-building and negotiation skills', 'Valid Australian driver''s licence', 'Self-motivated with a proven ability to hit sales targets', 'Proficiency in CRM tools and Microsoft Office']::text[], ARRAY['Commission structure on new accounts', 'Company vehicle', 'Expense account for client entertainment', 'Career path to Sales Manager']::text[], true, 10),
  (11, 'Marketing & Social Media Coordinator', 'Marketing', 'Part-Time / Full-Time', 'Hobart (Hybrid)', '$55,000 – $65,000 + super (pro-rata)', null, '', 'Tell the Saigon Express story to Tasmania and beyond. You will manage our social media presence, create content, run promotions, and help build one of Tasmania''s most loved food brands.', ARRAY['Plan, create, and schedule content across Instagram, Facebook, and TikTok', 'Photograph and film food, team, and behind-the-scenes content at our locations', 'Manage community engagement — respond to comments, DMs, and reviews', 'Plan and execute seasonal promotions, giveaways, and influencer partnerships', 'Write copy for the website, email newsletters, and in-store signage', 'Monitor analytics and report on content performance monthly', 'Assist with the design of menus, flyers, and marketing collateral', 'Support the franchise and wholesale teams with B2B marketing materials']::text[], ARRAY['Demonstrated experience managing social media for a food, hospitality, or lifestyle brand', 'Strong photography and basic video editing skills (Reels, TikTok)', 'Excellent copywriting ability — warm, engaging, and on-brand', 'Proficiency in Canva or Adobe Creative Suite', 'Passion for Vietnamese food culture and storytelling', 'Degree in Marketing, Communications, or a related field is advantageous']::text[], ARRAY['Hybrid work arrangement', '30% staff meal discount', 'Creative freedom to build the brand', 'Career path to Marketing Manager']::text[], true, 11),
  (12, 'Franchise Support Officer', 'Franchise', 'Full-Time', 'Hobart CBD', '$58,000 – $70,000 + super', null, '', 'Support the growth of the Saigon Express franchise network. You will be the primary point of contact for new and existing franchisees, helping them succeed through training, compliance, and operational support.', ARRAY['Onboard new franchisees through the full training and set-up process', 'Conduct regular store visits to assess compliance with brand standards and SOPs', 'Provide ongoing operational support and troubleshooting to franchisees', 'Maintain and update the Franchise Operations Manual and training materials', 'Coordinate the franchise application and approval process', 'Liaise with legal, finance, and marketing teams on behalf of franchisees', 'Prepare monthly performance reports for each franchise location']::text[], ARRAY['Experience in franchise operations, hospitality management, or a similar field', 'Strong interpersonal skills and ability to build trust with business owners', 'Highly organised with excellent written and verbal communication', 'Willingness to travel to franchise locations across Tasmania', 'Understanding of franchise agreements and compliance frameworks is advantageous']::text[], ARRAY['Travel allowance', 'Career path to Franchise Development Manager', 'Company phone and laptop', 'Paid professional development']::text[], true, 12);

select setval(
  pg_get_serial_sequence('public.job_listings', 'id'),
  (select coalesce(max(id), 1) from public.job_listings)
);
