-- Franchise interest submissions (public form: FranchisePage).

create type public.franchise_interest_status as enum (
  'pending',
  'approved',
  'resolved',
  'rejected'
);

create type public.franchise_interest_type as enum (
  'franchise',
  'consultation',
  'catering_enquiry'
);

create table public.franchise_interests (
  id bigint generated by default as identity primary key,
  interest_type public.franchise_interest_type not null default 'franchise',
  full_name text not null,
  email text not null,
  phone text,
  city text,
  state text,
  business_name text,
  investment_budget text,
  business_experience text,
  preferred_date date,
  preferred_time text,
  event_date date,
  guest_count integer,
  message text,
  status public.franchise_interest_status not null default 'pending',
  created_at timestamptz not null default now(),

  constraint franchise_interests_full_name_length check (
    char_length(trim(full_name)) between 1 and 128
  ),
  constraint franchise_interests_email_format check (
    email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
  ),
  constraint franchise_interests_phone_length check (
    phone is null or char_length(trim(phone)) between 1 and 32
  ),
  constraint franchise_interests_city_length check (
    city is null or char_length(trim(city)) between 1 and 128
  ),
  constraint franchise_interests_state_length check (
    state is null or char_length(trim(state)) between 1 and 64
  ),
  constraint franchise_interests_business_name_length check (
    business_name is null or char_length(trim(business_name)) between 1 and 128
  ),
  constraint franchise_interests_investment_budget_length check (
    investment_budget is null or char_length(trim(investment_budget)) between 1 and 128
  ),
  constraint franchise_interests_business_experience_length check (
    business_experience is null or char_length(trim(business_experience)) between 1 and 256
  ),
  constraint franchise_interests_preferred_time_length check (
    preferred_time is null or char_length(trim(preferred_time)) between 1 and 64
  ),
  constraint franchise_interests_guest_count_range check (
    guest_count is null or guest_count between 1 and 10000
  ),
  constraint franchise_interests_message_length check (
    message is null or char_length(trim(message)) between 1 and 4000
  )
);

comment on table public.franchise_interests is
  'Public interest submissions: franchise, consultation, and catering enquiry forms.';
comment on column public.franchise_interests.interest_type is
  'Submission type: franchise interest, consultation booking, or catering enquiry.';
comment on column public.franchise_interests.full_name is 'Applicant full name.';
comment on column public.franchise_interests.email is 'Applicant email address.';
comment on column public.franchise_interests.phone is 'Optional applicant phone number.';
comment on column public.franchise_interests.city is 'Optional city / location.';
comment on column public.franchise_interests.state is 'Applicant state/region (e.g. Tasmania).';
comment on column public.franchise_interests.business_name is
  'Organization or business name (catering enquiry).';
comment on column public.franchise_interests.investment_budget is 'Selected investment budget bracket.';
comment on column public.franchise_interests.business_experience is 'Applicant prior business experience payload.';
comment on column public.franchise_interests.preferred_date is 'Preferred consultation date.';
comment on column public.franchise_interests.preferred_time is 'Preferred consultation time window.';
comment on column public.franchise_interests.event_date is 'Catering event date.';
comment on column public.franchise_interests.guest_count is 'Expected catering guest count.';
comment on column public.franchise_interests.message is 'Freeform message.';
comment on column public.franchise_interests.status is 'Admin review status.';

create index franchise_interests_created_at_idx
  on public.franchise_interests (created_at desc);
create index franchise_interests_email_idx
  on public.franchise_interests (email);
create index franchise_interests_interest_type_idx
  on public.franchise_interests (interest_type);

alter table public.franchise_interests enable row level security;

revoke insert, update, delete on public.franchise_interests from anon, authenticated;

-- Admin can read / manage submissions (public submissions are RPC-only via submit_franchise_interest()).
grant select on public.franchise_interests to authenticated;
grant insert, update, delete on public.franchise_interests to authenticated;
grant all on public.franchise_interests to service_role;

create policy "Admins can read franchise interests"
  on public.franchise_interests
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert franchise interests"
  on public.franchise_interests
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update franchise interests"
  on public.franchise_interests
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete franchise interests"
  on public.franchise_interests
  for delete
  to authenticated
  using (public.is_admin());

create or replace function public.submit_franchise_interest(
  p_interest_type text,
  p_full_name text,
  p_email text,
  p_phone text,
  p_city text,
  p_state text,
  p_investment_budget text,
  p_business_experience text,
  p_preferred_date date,
  p_preferred_time text,
  p_message text,
  p_business_name text default null,
  p_event_date date default null,
  p_guest_count integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_interest_type public.franchise_interest_type := coalesce(
    nullif(trim(p_interest_type), '')::public.franchise_interest_type,
    'franchise'::public.franchise_interest_type
  );
  v_full_name text := nullif(trim(p_full_name), '');
  v_email text := nullif(trim(p_email), '');
  v_phone text := nullif(trim(p_phone), '');
  v_city text := nullif(trim(p_city), '');
  v_state text := coalesce(nullif(trim(p_state), ''), 'Tasmania');
  v_business_name text := nullif(trim(p_business_name), '');
  v_investment_budget text := nullif(trim(p_investment_budget), '');
  v_business_experience text := nullif(trim(p_business_experience), '');
  v_preferred_date date := p_preferred_date;
  v_preferred_time text := nullif(trim(p_preferred_time), '');
  v_event_date date := p_event_date;
  v_guest_count integer := p_guest_count;
  v_message text := nullif(trim(p_message), '');
  v_id bigint;
begin
  if v_full_name is null or v_email is null then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_email !~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$' then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_message is not null and char_length(trim(v_message)) < 1 then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_guest_count is not null and (v_guest_count < 1 or v_guest_count > 10000) then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_interest_type = 'consultation' then
    if v_phone is null or v_preferred_date is null then
      raise exception 'invalid request' using errcode = '22023';
    end if;
  end if;

  insert into public.franchise_interests (
    interest_type,
    full_name,
    email,
    phone,
    city,
    state,
    business_name,
    investment_budget,
    business_experience,
    preferred_date,
    preferred_time,
    event_date,
    guest_count,
    message
  )
  values (
    v_interest_type,
    v_full_name,
    v_email,
    v_phone,
    v_city,
    v_state,
    v_business_name,
    v_investment_budget,
    v_business_experience,
    v_preferred_date,
    v_preferred_time,
    v_event_date,
    v_guest_count,
    v_message
  )
  returning id into v_id;

  return jsonb_build_object(
    'id', v_id,
    'submitted', true
  );
end;
$$;

comment on function public.submit_franchise_interest(
  text, text, text, text, text, text, text, text, date, text, text, text, date, integer
) is
  'Inserts a franchise_interests row for public form submissions (franchise, consultation, or catering enquiry).';

grant execute on function public.submit_franchise_interest(
  text, text, text, text, text, text, text, text, date, text, text, text, date, integer
) to anon, authenticated;

