-- FAQ / public feedback submissions with IP-based rate limiting.
create table public.feedbacks (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  question text not null,
  source text not null default 'faq',
  ip_hash text not null,
  created_at timestamptz not null default now(),
  constraint feedbacks_name_length check (char_length(trim(name)) between 1 and 128),
  constraint feedbacks_email_length check (
    email is null or char_length(trim(email)) between 1 and 320
  ),
  constraint feedbacks_question_length check (char_length(trim(question)) between 10 and 1000),
  constraint feedbacks_source_allowed check (source in ('faq'))
);

comment on table public.feedbacks is
  'Public feedback and FAQ question submissions from the website.';
comment on column public.feedbacks.source is
  'Form origin identifier (e.g. faq).';
comment on column public.feedbacks.ip_hash is
  'SHA-256 hash of client IP (salted server-side); used for abuse prevention.';

create index feedbacks_created_at_idx on public.feedbacks (created_at desc);
create index feedbacks_source_created_at_idx on public.feedbacks (source, created_at desc);

alter table public.feedbacks enable row level security;

revoke insert, update, delete on public.feedbacks from anon, authenticated;
grant select on public.feedbacks to authenticated;

create policy "Admins can read feedbacks"
  on public.feedbacks
  for select
  to authenticated
  using (public.is_admin());

-- Rate-limit keys for feedback submissions (one row per ip hash).
create table public.feedback_rate_limits (
  ip_hash text not null primary key,
  last_submitted_at timestamptz not null default now()
);

comment on table public.feedback_rate_limits is
  'Rate-limit keys for feedback submissions (ip hash).';

create index feedback_rate_limits_last_submitted_at_idx
  on public.feedback_rate_limits (last_submitted_at);

alter table public.feedback_rate_limits enable row level security;

revoke all on public.feedback_rate_limits from anon, authenticated;
grant all on public.feedback_rate_limits to service_role;

create or replace function public.submit_feedback(
  p_name text,
  p_email text,
  p_question text,
  p_source text,
  p_ip_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := nullif(trim(p_name), '');
  v_email text := nullif(trim(p_email), '');
  v_question text := nullif(trim(p_question), '');
  v_source text := coalesce(nullif(trim(p_source), ''), 'faq');
  v_last_submitted_at timestamptz;
  v_feedback_id bigint;
begin
  if v_name is null
     or v_question is null
     or p_ip_hash is null
     or length(trim(p_ip_hash)) = 0 then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_source not in ('faq') then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_email is not null
     and v_email !~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$' then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  select last_submitted_at
  into v_last_submitted_at
  from public.feedback_rate_limits
  where ip_hash = p_ip_hash
  for update;

  if found and v_last_submitted_at >= now() - interval '5 minutes' then
    raise exception 'rate_limited' using errcode = 'P0001';
  end if;

  if not found then
    insert into public.feedback_rate_limits (ip_hash, last_submitted_at)
    values (p_ip_hash, now());
  else
    update public.feedback_rate_limits
    set last_submitted_at = now()
    where ip_hash = p_ip_hash;
  end if;

  insert into public.feedbacks (name, email, question, source, ip_hash)
  values (v_name, v_email, v_question, v_source, p_ip_hash)
  returning id into v_feedback_id;

  return jsonb_build_object(
    'id', v_feedback_id,
    'submitted', true
  );
end;
$$;

comment on function public.submit_feedback(text, text, text, text, text) is
  'Inserts a feedback row when the IP hash is outside the 5-minute rate limit.';

grant execute on function public.submit_feedback(text, text, text, text, text)
  to anon, authenticated;

-- Admin CRUD policies for feedbacks (public submissions remain RPC-only).
grant insert, update, delete on public.feedbacks to authenticated;

create policy "Admins can insert feedbacks"
  on public.feedbacks
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update feedbacks"
  on public.feedbacks
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete feedbacks"
  on public.feedbacks
  for delete
  to authenticated
  using (public.is_admin());
