-- Job application submissions (careers form: personal details, screening questions, review).

create type public.job_application_status as enum (
  'pending',
  'reviewing',
  'approved',
  'resolved',
  'rejected'
);

create table public.job_applications (
  id bigint generated by default as identity primary key,

  -- Posting context (from careers listing / apply flow)
  job_title text not null,
  job_location text,
  store_id bigint references public.store_locations (id) on delete set null,

  -- Step 1: Personal details
  legal_first_name text not null,
  legal_middle_names text,
  legal_last_name text not null,
  email text not null,
  phone text,
  resume_url text,
  resume_filename text,
  cover_letter_url text,
  cover_letter_filename text,
  agree_to_terms boolean not null default false,

  -- Step 2: Additional questions
  date_of_birth date,
  can_work_weekends text,
  commute_under_20_minutes text,
  work_availability text,

  -- Step 3: Review and submit
  candidate_message text,

  status public.job_application_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint job_applications_job_title_length check (
    char_length(trim(job_title)) between 1 and 256
  ),
  constraint job_applications_job_location_length check (
    job_location is null or char_length(trim(job_location)) between 1 and 256
  ),
  constraint job_applications_legal_first_name_length check (
    char_length(trim(legal_first_name)) between 1 and 128
  ),
  constraint job_applications_legal_middle_names_length check (
    legal_middle_names is null
    or char_length(trim(legal_middle_names)) between 1 and 128
  ),
  constraint job_applications_legal_last_name_length check (
    char_length(trim(legal_last_name)) between 1 and 128
  ),
  constraint job_applications_email_format check (
    email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
  ),
  constraint job_applications_phone_length check (
    phone is null or char_length(trim(phone)) between 1 and 32
  ),
  constraint job_applications_resume_url_length check (
    resume_url is null or char_length(trim(resume_url)) between 1 and 2048
  ),
  constraint job_applications_resume_filename_length check (
    resume_filename is null or char_length(trim(resume_filename)) between 1 and 256
  ),
  constraint job_applications_cover_letter_url_length check (
    cover_letter_url is null or char_length(trim(cover_letter_url)) between 1 and 2048
  ),
  constraint job_applications_cover_letter_filename_length check (
    cover_letter_filename is null
    or char_length(trim(cover_letter_filename)) between 1 and 256
  ),
  constraint job_applications_agree_to_terms_required check (agree_to_terms = true),
  constraint job_applications_dob_reasonable check (
    date_of_birth is null
    or (date_of_birth >= date '1900-01-01' and date_of_birth <= current_date)
  ),
  constraint job_applications_can_work_weekends_allowed check (
    can_work_weekends is null or can_work_weekends in ('Yes', 'No')
  ),
  constraint job_applications_commute_under_20_minutes_allowed check (
    commute_under_20_minutes is null
    or commute_under_20_minutes in ('Yes', 'No')
  ),
  constraint job_applications_work_availability_length check (
    work_availability is null
    or char_length(trim(work_availability)) between 1 and 2000
  ),
  constraint job_applications_candidate_message_length check (
    candidate_message is null
    or char_length(trim(candidate_message)) between 1 and 8000
  )
);

comment on table public.job_applications is
  'Careers job application submissions (personal details, screening answers, optional attachments).';
comment on column public.job_applications.job_title is
  'Position title the applicant applied for (e.g. Supervisor - Karingal Hub).';
comment on column public.job_applications.job_location is
  'Optional location label parsed from the posting.';
comment on column public.job_applications.store_id is
  'Optional link to store_locations when the posting maps to a store.';
comment on column public.job_applications.legal_first_name is 'Applicant legal first name.';
comment on column public.job_applications.legal_middle_names is 'Optional applicant middle name(s).';
comment on column public.job_applications.legal_last_name is 'Applicant legal last name.';
comment on column public.job_applications.email is 'Applicant email address.';
comment on column public.job_applications.phone is 'Optional applicant phone number.';
comment on column public.job_applications.resume_url is
  'Public or signed URL for uploaded resume (image, PDF, or Word doc).';
comment on column public.job_applications.resume_filename is 'Original resume filename.';
comment on column public.job_applications.cover_letter_url is
  'Public or signed URL for uploaded cover letter.';
comment on column public.job_applications.cover_letter_filename is 'Original cover letter filename.';
comment on column public.job_applications.agree_to_terms is
  'Applicant accepted recruiting terms and privacy collection notice.';
comment on column public.job_applications.date_of_birth is 'Applicant date of birth.';
comment on column public.job_applications.can_work_weekends is
  'Screening answer: Can you work weekends? (Yes/No).';
comment on column public.job_applications.commute_under_20_minutes is
  'Screening answer: Will your commute be 20 minutes or less? (Yes/No).';
comment on column public.job_applications.work_availability is
  'Screening answer: free-text work availability.';
comment on column public.job_applications.candidate_message is
  'Optional final message from the review-and-submit step.';
comment on column public.job_applications.status is 'Admin review status.';

create index job_applications_created_at_idx
  on public.job_applications (created_at desc);
create index job_applications_email_idx
  on public.job_applications (email);
create index job_applications_job_title_idx
  on public.job_applications (job_title);
create index job_applications_status_idx
  on public.job_applications (status);
create index job_applications_store_id_idx
  on public.job_applications (store_id);

create trigger job_applications_set_updated_at
  before update on public.job_applications
  for each row
  execute function public.set_updated_at();

alter table public.job_applications enable row level security;

revoke insert, update, delete on public.job_applications from anon, authenticated;

grant select on public.job_applications to authenticated;
grant insert, update, delete on public.job_applications to authenticated;
grant all on public.job_applications to service_role;

create policy "Admins can read job applications"
  on public.job_applications
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert job applications"
  on public.job_applications
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update job applications"
  on public.job_applications
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete job applications"
  on public.job_applications
  for delete
  to authenticated
  using (public.is_admin());

create or replace function public.submit_job_application(
  p_job_title text,
  p_legal_first_name text,
  p_legal_last_name text,
  p_email text,
  p_agree_to_terms boolean,
  p_job_location text default null,
  p_store_id bigint default null,
  p_legal_middle_names text default null,
  p_phone text default null,
  p_resume_url text default null,
  p_resume_filename text default null,
  p_cover_letter_url text default null,
  p_cover_letter_filename text default null,
  p_date_of_birth date default null,
  p_can_work_weekends text default null,
  p_commute_under_20_minutes text default null,
  p_work_availability text default null,
  p_candidate_message text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job_title text := nullif(trim(p_job_title), '');
  v_job_location text := nullif(trim(p_job_location), '');
  v_legal_first_name text := nullif(trim(p_legal_first_name), '');
  v_legal_middle_names text := nullif(trim(p_legal_middle_names), '');
  v_legal_last_name text := nullif(trim(p_legal_last_name), '');
  v_email text := nullif(trim(p_email), '');
  v_phone text := nullif(trim(p_phone), '');
  v_resume_url text := nullif(trim(p_resume_url), '');
  v_resume_filename text := nullif(trim(p_resume_filename), '');
  v_cover_letter_url text := nullif(trim(p_cover_letter_url), '');
  v_cover_letter_filename text := nullif(trim(p_cover_letter_filename), '');
  v_can_work_weekends text := nullif(trim(p_can_work_weekends), '');
  v_commute_under_20_minutes text := nullif(trim(p_commute_under_20_minutes), '');
  v_work_availability text := nullif(trim(p_work_availability), '');
  v_candidate_message text := nullif(trim(p_candidate_message), '');
  v_id bigint;
begin
  if v_job_title is null
     or v_legal_first_name is null
     or v_legal_last_name is null
     or v_email is null
     or coalesce(p_agree_to_terms, false) is distinct from true then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_email !~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$' then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_can_work_weekends is not null
     and v_can_work_weekends not in ('Yes', 'No') then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if v_commute_under_20_minutes is not null
     and v_commute_under_20_minutes not in ('Yes', 'No') then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  if p_date_of_birth is not null
     and (p_date_of_birth < date '1900-01-01' or p_date_of_birth > current_date) then
    raise exception 'invalid request' using errcode = '22023';
  end if;

  insert into public.job_applications (
    job_title,
    job_location,
    store_id,
    legal_first_name,
    legal_middle_names,
    legal_last_name,
    email,
    phone,
    resume_url,
    resume_filename,
    cover_letter_url,
    cover_letter_filename,
    agree_to_terms,
    date_of_birth,
    can_work_weekends,
    commute_under_20_minutes,
    work_availability,
    candidate_message
  )
  values (
    v_job_title,
    v_job_location,
    p_store_id,
    v_legal_first_name,
    v_legal_middle_names,
    v_legal_last_name,
    v_email,
    v_phone,
    v_resume_url,
    v_resume_filename,
    v_cover_letter_url,
    v_cover_letter_filename,
    true,
    p_date_of_birth,
    v_can_work_weekends,
    v_commute_under_20_minutes,
    v_work_availability,
    v_candidate_message
  )
  returning id into v_id;

  return jsonb_build_object(
    'id', v_id,
    'submitted', true
  );
end;
$$;

comment on function public.submit_job_application(
  text, text, text, text, boolean, text, bigint, text, text, text, text, text, text, date, text, text, text, text
) is
  'Inserts a job_applications row for public careers form submissions.';

grant execute on function public.submit_job_application(
  text, text, text, text, boolean, text, bigint, text, text, text, text, text, text, date, text, text, text, text
) to anon, authenticated;

-- Anonymous guest uploads for careers job application attachments.

create policy "Anyone can upload job application guest files"
  on storage.objects
  for insert
  to anon, authenticated
  with check (
    bucket_id = 'saigon-express-tasmania-customers'
    and (storage.foldername(name))[1] = 'job-applications'
    and (storage.foldername(name))[2] = 'guest'
  );

create policy "Anyone can read job application guest files"
  on storage.objects
  for select
  to anon, authenticated
  using (
    bucket_id = 'saigon-express-tasmania-customers'
    and (storage.foldername(name))[1] = 'job-applications'
    and (storage.foldername(name))[2] = 'guest'
  );


