-- Wholesale bulk-pricing tiers shown on the public wholesale shop page.

create table public.wholesale_tiers (
  id bigint generated by default as identity primary key,
  label text not null unique,
  min_value numeric(10, 2) not null default 0.00,
  discount_value numeric(10, 2) not null default 0.00,
  color text not null,
  popular boolean not null default false,
  sort_order integer not null default 0
);

comment on table public.wholesale_tiers is
  'Bulk-pricing tiers displayed on the public wholesale shop pricing section.';

comment on column public.wholesale_tiers.min_value is
  'Minimum order subtotal (AUD) required to qualify for this tier discount.';

comment on column public.wholesale_tiers.discount_value is
  'Discount percentage applied at checkout when the order meets min_value.';

comment on column public.wholesale_tiers.color is
  'Tailwind gradient classes for the tier card background.';

create index wholesale_tiers_sort_order_idx
  on public.wholesale_tiers (sort_order, id);

alter table public.wholesale_tiers enable row level security;

create policy "Anyone can read wholesale tiers"
  on public.wholesale_tiers
  for select
  to anon, authenticated
  using (true);

grant select on public.wholesale_tiers to anon, authenticated;
grant insert, update, delete on public.wholesale_tiers to authenticated;
grant all on public.wholesale_tiers to service_role;

-- Admin CRUD
create policy "Admins can read all wholesale tiers"
  on public.wholesale_tiers
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert wholesale tiers"
  on public.wholesale_tiers
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update wholesale tiers"
  on public.wholesale_tiers
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete wholesale tiers"
  on public.wholesale_tiers
  for delete
  to authenticated
  using (public.is_admin());

-- Seed from messages/en.json → WholesaleShop.pricingTiers
insert into public.wholesale_tiers (
  label,
  min_value,
  discount_value,
  color,
  popular,
  sort_order
)
values
  (
    'Standard',
    0.00,
    0.00,
    'from-white/5 to-white/10',
    false,
    0
  ),
  (
    'Bronze',
    500.00,
    5.00,
    'from-amber-900/30 to-amber-800/20',
    false,
    1
  ),
  (
    'Silver',
    1000.00,
    10.00,
    'from-slate-600/30 to-slate-500/20',
    false,
    2
  ),
  (
    'Gold',
    2500.00,
    15.00,
    'from-amber-500/45 to-yellow-500/30',
    true,
    3
  ),
  (
    'Platinum',
    5000.00,
    25.00,
    'from-primary/30 to-primary/20',
    false,
    4
  )
on conflict (label) do update set
  min_value = excluded.min_value,
  discount_value = excluded.discount_value,
  color = excluded.color,
  popular = excluded.popular,
  sort_order = excluded.sort_order;
