-- Saigon Express catering catalogue (packs, boxes, hot dishes & platters).
-- Product ids: 621001..621004 (packs), 622001..622018 (boxes & platters).
-- Avoids collision with Chao catering (61xxxx) and Catering Project bulk (620001..620476).

insert into public.products (
  id,
  product_type,
  name,
  category,
  description,
  uom,
  is_available,
  sort_order,
  image_urls,
  price,
  unit_price,
  wholesale_price,
  prices,
  slug,
  is_catch_weight,
  related_items,
  is_popular,
  ingredients,
  sku,
  unit,
  daily_global_limit,
  daily_customer_limit,
  min_order_qty,
  serves,
  includes,
  tag,
  tag_bg,
  note,
  image_url,
  created_at,
  updated_at
)
values
  (
    621001,
    'catering'::public.product_type,
    'Office Starter Pack',
    'Catering Packs',
    'A selection of our signature bánh mì, fresh spring rolls, and homemade drinks — perfect for team lunches and morning meetings.',
    'EACH'::public.product_uom,
    true,
    0,
    '{}'::jsonb,
    'From $8.50/person',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-621001',
    '',
    null,
    null,
    1,
    '10–20 guests',
    '["Choice of 3 bánh mì varieties","Fresh rice paper rolls","Homemade lemongrass drinks","Napkins & serving trays"]'::jsonb,
    'MOST POPULAR',
    'bg-brand-red',
    null,
    '/manus-storage/banh-mi-1_9ba4dcf0.jpg',
    now(),
    now()
  ),
  (
    621002,
    'catering'::public.product_type,
    'Event Feast Pack',
    'Catering Packs',
    'A full Vietnamese spread with bánh mì, phở, bún bowls, and entrée platters — ideal for corporate events, birthdays, and celebrations.',
    'EACH'::public.product_uom,
    true,
    1,
    '{}'::jsonb,
    'From $12/person',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-621002',
    '',
    null,
    null,
    1,
    '30–60 guests',
    '["Full bánh mì bar (5 varieties)","Phở or bún bowl station","Entrée platters","Dessert rice paper rolls","Full service setup"]'::jsonb,
    'BEST VALUE',
    'bg-brand-amber',
    null,
    '/manus-storage/pho-1_92a9985e.jpg',
    now(),
    now()
  ),
  (
    621003,
    'catering'::public.product_type,
    'Corporate Catering',
    'Catering Packs',
    'Tailored menus for large corporate functions, conferences, and gala dinners. Includes dedicated staff, full setup, and branded presentation.',
    'EACH'::public.product_uom,
    true,
    2,
    '{}'::jsonb,
    'Custom quote',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-621003',
    '',
    null,
    null,
    1,
    '50–200 guests',
    '["Fully customised menu","Dedicated catering staff","Premium branded presentation","Dietary accommodations","Post-event cleanup"]'::jsonb,
    'PREMIUM',
    'bg-brand-dark',
    null,
    '/manus-storage/bun-bowl-1_3b12ea6c.jpg',
    now(),
    now()
  ),
  (
    621004,
    'catering'::public.product_type,
    'Custom Pack',
    'Catering Packs',
    'Have something specific in mind? We''ll build a package around your event, dietary needs, and budget. No event is too big or too small.',
    'EACH'::public.product_uom,
    true,
    3,
    '{}'::jsonb,
    'Get a quote',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-621004',
    '',
    null,
    null,
    1,
    'Any size',
    '["Fully flexible menu","Any dietary requirement","Any event size","Delivery or pick-up","Personal consultation"]'::jsonb,
    'FLEXIBLE',
    'bg-brand-dark/70',
    null,
    '/manus-storage/spring-rolls-1_02f22814.jpg',
    now(),
    now()
  ),
  (
    622001,
    'catering'::public.product_type,
    'Saigon Feast Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    0,
    '{}'::jsonb,
    '$160',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622001',
    '',
    null,
    null,
    1,
    '8–10 People',
    '["8 x Mini Bowls","8 x Fresh Rice Paper Rolls cut in half","6 x Mini Banh Mi","4 x Bao Buns"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/SaigonFeastBox_6c26a5d8.jpg',
    now(),
    now()
  ),
  (
    622002,
    'catering'::public.product_type,
    'Rice Paper Roll Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    1,
    '{}'::jsonb,
    '$130',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622002',
    '',
    null,
    null,
    1,
    '8–10 People',
    '["28 x Standard Saigon RPR served with a variety of delicious sauces"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/Ricepaperrollplatter_b21700d4.jpg',
    now(),
    now()
  ),
  (
    622003,
    'catering'::public.product_type,
    'Spring Roll Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    2,
    '{}'::jsonb,
    '$115',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622003',
    '',
    null,
    null,
    1,
    '6–8 People',
    '["20 x Vegan Spring Roll","30 x Seafood Spring Roll"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/Springrollplatter_c7f62c18.jpg',
    now(),
    now()
  ),
  (
    622004,
    'catering'::public.product_type,
    'Mixed Entrée Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    3,
    '{}'::jsonb,
    '$115',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622004',
    '',
    null,
    null,
    1,
    '6–8 People',
    '["10 x Vegan Spring Roll","10 x Seafood Spring Roll","10 x Prawn Toast","10 x Fried Pork and Chive Dumpling"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/MixedEntreePlatter_983d3d92.jpg',
    now(),
    now()
  ),
  (
    622005,
    'catering'::public.product_type,
    'Saigon Lunch Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    4,
    '{}'::jsonb,
    '$140',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622005',
    '',
    null,
    null,
    1,
    '6–8 People',
    '["10 x Mixed Mini Bowls","10 x Mixed Mini Banh Mi"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/BowlsBox_575d600e.jpg',
    now(),
    now()
  ),
  (
    622006,
    'catering'::public.product_type,
    'Steamed Bao Bun Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    5,
    '{}'::jsonb,
    '$130',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622006',
    '',
    null,
    null,
    1,
    '6–8 People',
    '["20 x Mixed Bao Buns","Available in a variety of flavours"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/SteamedBaoBunPlatter_3c06d7a4.jpg',
    now(),
    now()
  ),
  (
    622007,
    'catering'::public.product_type,
    'Saigon Bánh Mì Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    6,
    '{}'::jsonb,
    '$150',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622007',
    '',
    null,
    null,
    1,
    '6–8 People',
    '["30 x Mini Bánh Mì Baguettes","Available in a variety of flavours"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/SaigonBanhMiBox_94e826fc.jpg',
    now(),
    now()
  ),
  (
    622008,
    'catering'::public.product_type,
    'Saigon Street Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    7,
    '{}'::jsonb,
    '$140',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622008',
    '',
    null,
    null,
    1,
    '6–8 People',
    '["15 x Mixed Mini Bánh Mì","20 x Mixed Saigon Rolls"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/BanhMi&FreshrollsBox_ca58276a.jpg',
    now(),
    now()
  ),
  (
    622009,
    'catering'::public.product_type,
    'Mini Bowls Box',
    'Catering Boxes',
    '',
    'EACH'::public.product_uom,
    true,
    8,
    '{}'::jsonb,
    '$130',
    '',
    null,
    '[]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622009',
    '',
    null,
    null,
    1,
    '8–10 People',
    '["20 x Mini Bowls","A mix of Gỏi (Viet Salad), Bún (Noodle Salad) and Cơm (Rice)"]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/MiniBanhMiBox_5a74c97a.jpg',
    now(),
    now()
  ),
  (
    622010,
    'catering'::public.product_type,
    'Saigon Fried Rice',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    9,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$65","serves":"5–7 People"},{"size":"Medium","price":"$95","serves":"8–12 People"},{"size":"Large","price":"$125","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622010',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/SaigonFriedRice_48676d3d.jpg',
    now(),
    now()
  ),
  (
    622011,
    'catering'::public.product_type,
    'Vietnamese Salad',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    10,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$35","serves":"5–7 People"},{"size":"Medium","price":"$55","serves":"8–12 People"},{"size":"Large","price":"$75","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622011',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/VietnameseSalad_cb8a745b.jpg',
    now(),
    now()
  ),
  (
    622012,
    'catering'::public.product_type,
    'Steamed Jasmine Rice',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    11,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$28","serves":"5–7 People"},{"size":"Medium","price":"$42","serves":"8–12 People"},{"size":"Large","price":"$55","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622012',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/SteamedJasmineRice_f5e40e3e.jpg',
    now(),
    now()
  ),
  (
    622013,
    'catering'::public.product_type,
    'Roast Pork Platter',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    12,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$65","serves":"5–7 People"},{"size":"Medium","price":"$95","serves":"8–12 People"},{"size":"Large","price":"$125","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622013',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/RoastPorkPlatter_d7881898.jpg',
    now(),
    now()
  ),
  (
    622014,
    'catering'::public.product_type,
    'Roast Pork & Roast Duck Platter',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    13,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$95","serves":"5–7 People"},{"size":"Medium","price":"$138","serves":"8–12 People"},{"size":"Large","price":"$180","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622014',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/RoastPorkDuckPlatter_739f3dd1.jpg',
    now(),
    now()
  ),
  (
    622015,
    'catering'::public.product_type,
    'Roast Pork & BBQ Pork Platter',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    14,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$80","serves":"5–7 People"},{"size":"Medium","price":"$118","serves":"8–12 People"},{"size":"Large","price":"$155","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622015',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/RoastPorkBBQPorkPlatter_8d0da620.jpg',
    now(),
    now()
  ),
  (
    622016,
    'catering'::public.product_type,
    'Stir-Fried Noodles',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    15,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$82","serves":"5–7 People"},{"size":"Medium","price":"$120","serves":"8–12 People"},{"size":"Large","price":"$158","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622016',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    'Choice of: Singapore Noodles · Soft Egg Noodles · Flat Rice Noodles',
    '/manus-storage/StirFriedNoodles_23279f91.jpg',
    now(),
    now()
  ),
  (
    622017,
    'catering'::public.product_type,
    'Stir-Fried Hot Dish',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    16,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$82","serves":"5–7 People"},{"size":"Medium","price":"$120","serves":"8–12 People"},{"size":"Large","price":"$158","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622017',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/StirFriedHotDish_16c653d6.jpg',
    now(),
    now()
  ),
  (
    622018,
    'catering'::public.product_type,
    'Stir-Fried Mixed Vegetables with Tofu',
    'Hot Dishes & Platters',
    '',
    'EACH'::public.product_uom,
    true,
    17,
    '{}'::jsonb,
    '',
    '',
    null,
    '[{"size":"Small","price":"$60","serves":"5–7 People"},{"size":"Medium","price":"$88","serves":"8–12 People"},{"size":"Large","price":"$115","serves":"15–20 People"}]'::jsonb,
    '',
    false,
    '{}'::bigint[],
    false,
    '[]'::jsonb,
    'CT-622018',
    '',
    null,
    null,
    1,
    null,
    '[]'::jsonb,
    '',
    '',
    null,
    '/manus-storage/StirFriedVegTofu_5daed2ed.jpg',
    now(),
    now()
  )
on conflict (id) do update set
  product_type = excluded.product_type,
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  uom = excluded.uom,
  is_available = excluded.is_available,
  sort_order = excluded.sort_order,
  image_urls = excluded.image_urls,
  price = excluded.price,
  unit_price = excluded.unit_price,
  wholesale_price = excluded.wholesale_price,
  prices = excluded.prices,
  slug = excluded.slug,
  is_catch_weight = excluded.is_catch_weight,
  related_items = excluded.related_items,
  is_popular = excluded.is_popular,
  ingredients = excluded.ingredients,
  sku = coalesce(nullif(trim(products.sku), ''), excluded.sku),
  unit = excluded.unit,
  daily_global_limit = excluded.daily_global_limit,
  daily_customer_limit = excluded.daily_customer_limit,
  min_order_qty = excluded.min_order_qty,
  serves = excluded.serves,
  includes = excluded.includes,
  tag = excluded.tag,
  tag_bg = excluded.tag_bg,
  note = excluded.note,
  image_url = excluded.image_url,
  updated_at = now();
