-- Wholesale bulk-pricing tiers shown on the public wholesale shop page.

create table public.wholesale_tiers (
  id bigint generated by default as identity primary key,
  label text not null unique,
  min_units text not null,
  discount text not null,
  color text not null,
  popular boolean not null default false,
  sort_order integer not null default 0
);

comment on table public.wholesale_tiers is
  'Bulk-pricing tiers displayed on the public wholesale shop pricing section.';

comment on column public.wholesale_tiers.min_units is
  'Human-readable minimum order quantity range (e.g. "10–24 units").';

comment on column public.wholesale_tiers.color is
  'Tailwind gradient classes for the tier card background.';

create index wholesale_tiers_sort_order_idx
  on public.wholesale_tiers (sort_order, id);

alter table public.wholesale_tiers enable row level security;

create policy "Anyone can read wholesale tiers"
  on public.wholesale_tiers
  for select
  to anon, authenticated
  using (true);

grant select on public.wholesale_tiers to anon, authenticated;
grant insert, update, delete on public.wholesale_tiers to authenticated;
grant all on public.wholesale_tiers to service_role;

-- Admin CRUD
create policy "Admins can read all wholesale tiers"
  on public.wholesale_tiers
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can insert wholesale tiers"
  on public.wholesale_tiers
  for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update wholesale tiers"
  on public.wholesale_tiers
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete wholesale tiers"
  on public.wholesale_tiers
  for delete
  to authenticated
  using (public.is_admin());

-- Seed from messages/en.json → WholesaleShop.pricingTiers
insert into public.wholesale_tiers (
  label,
  min_units,
  discount,
  color,
  popular,
  sort_order
)
values
  (
    'Standard',
    '1–9 units',
    '0%',
    'from-white/5 to-white/10',
    false,
    0
  ),
  (
    'Bronze',
    '10–24 units',
    '5% off',
    'from-amber-900/30 to-amber-800/20',
    false,
    1
  ),
  (
    'Silver',
    '25–49 units',
    '10% off',
    'from-slate-600/30 to-slate-500/20',
    false,
    2
  ),
  (
    'Gold',
    '50–99 units',
    '15% off',
    'from-yellow-700/30 to-yellow-600/20',
    true,
    3
  ),
  (
    'Platinum',
    '100+ units',
    '25% off',
    'from-primary/30 to-primary/20',
    false,
    4
  )
on conflict (label) do update set
  min_units = excluded.min_units,
  discount = excluded.discount,
  color = excluded.color,
  popular = excluded.popular,
  sort_order = excluded.sort_order;
